### ISSUE TITLE
Using System.IO classes interchangeably at runtime

### ISSUE THREAD

**Issue by catester** [alphaleonis/AlphaFS#103]
I know classes like System.IO.FileInfo are sealed and there are no interfaces so not sure if this may be possible. I consider using AlphaFS classes (which requires full trust) and fallback to System.IO counterparts only when it's a partial trust environment. Do you think it may be possible in any way without duplicating code and using lots of branching?

**Comment by alphaleonis** [comment]
I'm not sure I quite understand what you're asking here? I don't think there's a way to dynamically select which implementation to use in the way you describe I'd I understand you correctly though. You would probably have to create some facade through which you invoke file system related operations that selected the correct implementation depending on the environment.
