### ISSUE TITLE
VolumeInfo.Refresh() fails with System.IO.IOException: (234)

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#104]
If I call this method on some systems, I get this error message (more data available). 
Regarding this error I found this german post: 
https://www.overclockers.at/include_coding_stuff/win32api_experten-frage_122340?postid=1597458
The quintessence seems to be, that the buffer lengths given were not sufficient. In AlphaFS pre 1.5 there was a capacity of "NativeMethods.MAX_PATH + 1" now it is "NativeMethods.MaxPath/32". Can this cause the error?

**Comment by Yomodo** [comment]
Confirmed.

**Comment by Yomodo** [comment]
Fixed with commit: 4da11066c75934d6bd4eaa588aa29ad318ff3cbc

**Comment by alphaleonis** [comment]
@Yomodo Wasn't this fixed in 2.0.1 (on the master branch)? If so, the changelog should be updated to reflect this. (Also the changelog on the develop branch indicates that it was fixed in 2.1 while it should be 2.0.1.

**Comment by alphaleonis** [comment]
@Yomodo Feel free to close this again now that the changelog is updated unless there are other fixes to do on it.
