### ISSUE TITLE
Request for new Methods

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#105]
To use AlphaFS I would need the following methods and properties:
To easy access the underlying UTC dates rather than conversion to local time:

```
FileSystemEntryInfo.CreatedUtc
FileSystemEntryInfo.LastAccessedUtc
FileSystemEntryInfo.LastModifiedUtc
```

To open and create files with extended file attributes (e.g. Overlapped API) and buffer size:
`File.Create(string path, int bufferSize, FileMode mode, FileAccess access, FileShare share, ExtendedFileAttributes options, PathFormat pathFormat)`

`File.Open(string path, int bufferSize, FileMode mode, FileAccess access, FileShare share, ExtendedFileAttributes extendedAttributes, PathFormat pathFormat)`

Note: File.Open needs to create an FileStream with the isAsync-flag set to "true". 
But I have problems with overlapped-I/O and read-only volumes (e.g. Shadow-Copies).
File.Open results in error-messages "media is read-only", even if i open the file only read. The error disappears, if i don't use overlapped i/o. Perhaps one can give me also a hint on that.

Besides these findings: nice library! Refactoring from 1.0 to 2.0 took some time...

Lupinho.

**Comment by Yomodo** [comment]
Regarding the UTC dates, couldn't you use something like: ```FileSystemEntryInfo.Created.ToUniversalTime()``` ?

**Comment by alphaleonis** [comment]
Added issues #111 and #112 which should address the concerns in this issue. 
@Lupinho Thanks for the suggestions.

**Comment by Lupinho** [comment]
Can you give me hints to solve the problem with the overlapped I/O?

**Comment by alphaleonis** [comment]
Haven't tried that, so I don't know what to make of that really.  @Yomodo  do you have any ideas?

**Comment by Yomodo** [comment]
Unfortunately, no.

But I have this bookmark which I saved to study sometime:
http://www.beefycode.com/post/Using-Overlapped-IO-from-Managed-Code.aspx

**Comment by alphaleonis** [comment]
Created #116 to verify and fix the problem with overlapped support and read-only volumes.
