### ISSUE TITLE
Volume.Refresh() should throw DeviceNotReadyException

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#108]
AlphaFS 1.5 throws a DeviceNotReadyException on error 21.

**Comment by Yomodo** [comment]
Fixed with commit: 4da11066c75934d6bd4eaa588aa29ad318ff3cbc

**Comment by alphaleonis** [comment]
@Yomodo Wasn't this fixed in 2.0.1 (on the master branch)? If so, the changelog should be updated to reflect this. (Also the changelog on the develop branch indicates that it was fixed in 2.1 while it should be 2.0.1.

**Comment by alphaleonis** [comment]
@T

**Comment by alphaleonis** [comment]
@Yomodo Feel free to close this again now that the changelog is updated unless there are other fixes to do on it.
