### ISSUE TITLE
Add overloads of File.Open that allows specifying buffer size.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#111]
Don't know why we missed these, but they should be added.

See #105

**Comment by alphaleonis** [comment]
@Yomodo Hey, do you mind reviewing the changes I made to the **feature/file-open-buffersize** branch regarding this issue? I don't want it merged yet, I will continue by splitting the File.Open file into multiple files because it got kind of large as well, but thought it'd be easier to review before doing that.

**Comment by Yomodo** [comment]
Yeah, I'll look at it later today.

**Comment by Yomodo** [comment]
.NET originally has 3 `File.Open()` methods.
AlphaFS will have a total of 46 `File.Open()` methods. :no_mouth:

Isn't that a bit too much/overwhelming?

I think we should, of course, implement the .NET versions and AlphaFS Transacted versions thereof.

For the other overloaded methods, perhaps we should consider something like a `FileOpenOptions`
struct which hosts all the possible parameters.  Similar to `DirectoryEnumerationOptions` and `PathFormat`, although those are `enum`s.

**Comment by alphaleonis** [comment]
One reason for the added amount is that we need to take all the overloads of the `FileStream` constructor as well, since these also are used for opening files in .NET, so comparing with the .NET `File.Open` only is not really fair.

But yeah, 46 methods is a bit much, I agree.

I'm thinking of just splitting them in half by doing a File.OpenTransacted() or something instead, which would give it 23 overloads then which should be more manageable.  I'm not a big fan of the options classes, it is a bit hard to create because of the mutually exclusive options that are available.

**Comment by Yomodo** [comment]
I like the idea of prefixing the Transacted methods with `Transacted`
But, if we do it for `File.Open()` we should be consistent and rename _all_ other methods also, in time?

**Comment by alphaleonis** [comment]
Yeah, that's probably not a bad idea considering that there are quite a lot of overloads now.  Of course, it is quite a major breaking change, though I*m not sure how widespread the use of it is since microsoft "kind of deprecated" the feature.   Perhaps it is something we should do?

**Comment by Yomodo** [comment]
I think now (as in 2.1) would certainly be the time.

As a side note, look at: `Directory.CreateDirectory()`
Currently **32** methods of CreateDirectory-fu I'm not really happy with.

**Comment by Yomodo** [comment]
Regarding Transaction, we should keep supporting it as long as it is available?
We've already have methods nicely worked out, so why not.

**Comment by alphaleonis** [comment]
Yeah, absolutely, we'll keep supporting transactions as long as Windows supports them. But yeah, sounds like a good idea to split these into separate methods. Let's create a separate issue for that, and leave it out of this one though.  I take it everything looked okay otherwise?

**Comment by Yomodo** [comment]
Regarding `File.Open()`?  Yes, good to go!

**Comment by Yomodo** [comment]
How about a separate **Transactional** namespace, to host all those methods that support transactions.

**Comment by alphaleonis** [comment]
That would mean creating a whole new class hiearchy... seems overkill if you ask me.
