### ISSUE TITLE
Add CreationTimeUtc, LastAccessTimeUtc and LastWriteTimeUtc to "Info" classes.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#112]
These should be added to the following classes:
- `FileSystemEntryInfo`
- `ByHandleFileInfo`
- `FileIdBothDirectoryInfo`

This because it is likely much more performant than first converting to local time (as these properties do now) and then manually converting back to UTC.

It is also more in line with the FileInfo/DirectoryInfo classes.

See #105

**Comment by Yomodo** [comment]
Should we also do this for classes `ByHandleFileInfo`, `FileIdBothDirectoryInfo` ?

**Comment by alphaleonis** [comment]
@Yomodo Yup, good call, I've updated the issue.
