### ISSUE TITLE
It does not seem to be possible to encrypt/decrypt a directory without also encrypting the files within it?

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#122]
The `Directory.Encrypt` and `Directory.Decrypt` methods have an option `recursive` to indicate that you want the change to apply to subfolders as well. But it is always recursive in the sense that the files currently in the directory are encrypted (at the top level). 

In Windows it is actually quite possible to enable encryption on the directory only, without affecting the files, shouldn't this be the case also with AlphaFS then?

@Yomodo  any thoughts?

**Comment by Yomodo** [comment]
True, if non-recursive, it should only encrypt the given folder, NOT its contents (root items)

Created issue #123
