### ISSUE TITLE
Can you avoid CLSCompliant(false) for whole assembly?

### ISSUE THREAD

**Issue by catester** [alphaleonis/AlphaFS#125]
Is it necessary to apply this attribute to the AlphaFS assembly? You can already apply it at class or member level. Possibly you need this attribute for Native related classes/members and only if they are public.

When I reference AlphaFS assembly and only use simple public classes like FileInfo or DirectoryInfo in my own assembly with CLSCompliant(true), I get compiler warnings so it breaks my assembly's compliance.

I recommend you to set CLSCompliant(true) for the AlphaFS assembly temporarily and compile and examine the warnings case by case and set CLSCompliant(false) for the required classes/members only. I think there shouldn't be so many of them.

**Comment by alphaleonis** [comment]
@catester Or you could send us a pull-request with the changes required? ;)

**Comment by catester** [comment]
Ok :) I will look into it.

**Comment by alphaleonis** [comment]
Fixed with commit e1b2bba8d01d2b9595173b255bfc34db28238084
