### ISSUE TITLE
Script exits on exception "Access-Denied"

### ISSUE THREAD

**Issue by rzeygerman** [alphaleonis/AlphaFS#137]
Pwershell 2.0 witth AlphaFS.dll vs2.0
This code keeps exiting when it encounters "access-denied" exception to a folder. How can I make it continue?
# Load Assembly DLL
# Initialize Variables

$Path = "D:\"
# Read all folders into $Folders Array Variable

$Folders= [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($Path,"*","AllDirectories") 
# Display each Folder

Foreach ($Folder in $Folders) 
{
get-acl $Folder
}

**Comment by Yomodo** [comment]
You need a try/catch construct:
http://blogs.technet.com/b/heyscriptingguy/archive/2010/03/11/hey-scripting-guy-march-11-2010.aspx

**Comment by Yomodo** [comment]
Also please check out Wiki: https://github.com/alphaleonis/AlphaFS/wiki/PowerShell

You current PowerShell code is not going to last:

`#Read all folders into $Folders Array Variable`
`$Folders= ...`

**Comment by rzeygerman** [comment]
Try Catch is still crashing with Accedd-Denied

Try{
AllFilesArray=Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*","AllDirectories")}
 Catch [system.exception]
{ }
Finally
{
 Foreach ($file in $AllFilesArray) { $file} 
}

**Comment by Yomodo** [comment]
Your PowerShell code should be something like this:

```
Try {
    $array = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*","AllDirectories")
    Foreach ($file in $array) { $file } 
}
Catch { }
```

Or:

```
Try {
    $array = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*","AllDirectories")
    Foreach ($file in $array) { $file } 
}
Catch [System.UnauthorizedAccessException] {
    # Report exception.
}
```

**Comment by rzeygerman** [comment]
Thank you Jeffrey, 

I really appreciate you trying to help with this. I am a newbie, but its not my first "scripting" rodeo. This in my opinion should not be as complected as it is turning out to be...

I actually tried using both options you gave me with 3 different approaches to get the paths:

$Array=[Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"_","AllDirectories")  
$Array=[Alphaleonis.Win32.Filesystem.Directory]::EnumerateFileSystemEntries($StartPath, '_',"AllDirectories")  
$Array=[Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath, '*',"AllDirectories")

in one case (GetDirectories) i do not get any output
in case of the two Enumerate commands, I get partial result only.

I also tried to do the following and results are exactly the same.

Try {
       $Array = [Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath,"*","AllDirectories")
       Try {
               Foreach ($file in $AllFilesArray) { $file } }
               Catch [System.UnauthorizedAccessException] {}
       }
Catch [System.UnauthorizedAccessException]{$Error} 

Finally expanded the Catch to handle all 3 errors/exceptions and still received zero output

Try {
    $Array = [Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath,"*","AllDirectories")
    Try {Foreach ($file in $AllFilesArray) { $file } }
    Catch [System.UnauthorizedAccessException], [System.MethodInvocationException],[System.RuntimeException]{ }
Catch { }

**Comment by Yomodo** [comment]
Hi,

I think I see the error now: `AllDirectories` is invalid. :smile: 

It should be either: `System.IO.SearchOption.TopDirectoryOnly` or `System.IO.SearchOption.AllDirectories`

E.g.: `[Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath,"*", [System.IO.SearchOption]::AllDirectories)`

**Comment by Yomodo** [comment]
Correction, should be: `[System.IO.SearchOption]::AllDirectories`

**Comment by rzeygerman** [comment]
now, that's not it :-(

using powershell 2.0 / AlphaFS 2.0  (in case i haven't mentioned it)

error message using Array = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*","System.IO.SearchOption.AllDirectories")

Cannot convert argument "2", with value: "System.IO.SearchOption.AllDirectories", for "GetDirectories" to type "System.IO.SearchOption": "Cannot conver
t value "System.IO.SearchOption.AllDirectories" to type "System.IO.SearchOption" due to invalid enumeration values. Specify one of the following enumer
ation values and try again. The possible enumeration values are "TopDirectoryOnly, AllDirectories"."
At C:\Users\rzeygerman\AppData\Local\Temp\tmp3107.ps1:15 char:75

I am actually testing on the "c:\user\user_account folder" when the script runs, it exits when looking inside the "c:\users\user_account\app data\" and does not complete.

**Comment by Yomodo** [comment]
Type it literally like this: **[System.IO.SearchOption]::AllDirectories**
But do **not** put it between `""`

Copy/paste this line. I tested it and it works:

`[Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath,"*", [System.IO.SearchOption]::AllDirectories)`

**Comment by rzeygerman** [comment]
Thank you, [System.IO.SearchOption]::AllDirectories did replace "AllDirectories" and executed with the error below

Exception calling "GetDirectories" with "3" argument(s): "(5) Access is denied: [\?\c:\users\rzeygerman\Application Data]"
At C:\Users\rzeygerman\AppData\Local\Temp\tmp3107.ps1:15 char:75
-  $AllFilesArray = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories <<<< ($StartPath,"*",[System.IO.SearchOption]::AllDirectories)
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

when I  put the code back into the Try Catch, output was nothing 

 Try
 {$AllFilesArray = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*",[System.IO.SearchOption]::AllDirectories)
 Foreach ($file in $AllFilesArray) { $file }
 }
Catch { } 

when tried:

 Try
 {AllFilesArray = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*",[System.IO.SearchOption]::AllDirectories)
 Foreach ($file in $AllFilesArray) { $file }
 }
 Catch  [System.UnauthorizedAccessException]{ } 

Error:

The term 'AllFilesArray' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
 path was included, verify that the path is correct and try again.
At C:\Users\rzeygerman\AppData\Local\Temp\tmp3107.ps1:17 char:16
-  {AllFilesArray <<<<  = [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories($StartPath,"*",[System.IO.SearchOption]::AllDirectories)
  - CategoryInfo          : ObjectNotFound: (AllFilesArray:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

-----Original Message-----

**Comment by Yomodo** [comment]
You forgot the **$**AllFilesArray

**Comment by rzeygerman** [comment]
It did work, and gave me again, the exact "partial result" i was receiving before: (notice how it never gets any folders passed "AppData\Roaming" and never get to the inside of the Desktop Folder.

c:\users\rzeygerman\AlphaFS-2.0.0
c:\users\rzeygerman\ALTools
c:\users\rzeygerman\AppData
c:\users\rzeygerman\Application Data
c:\users\rzeygerman\Contacts
c:\users\rzeygerman\Cookies
c:\users\rzeygerman\Desktop
c:\users\rzeygerman\Documents
c:\users\rzeygerman\Downloads
c:\users\rzeygerman\Favorites
c:\users\rzeygerman\Links
c:\users\rzeygerman\Local Settings
c:\users\rzeygerman\Music
c:\users\rzeygerman\My Documents
c:\users\rzeygerman\NetHood
c:\users\rzeygerman\Pictures
c:\users\rzeygerman\PrintHood
c:\users\rzeygerman\Recent
c:\users\rzeygerman\Roaming
c:\users\rzeygerman\Saved Games
c:\users\rzeygerman\Searches
c:\users\rzeygerman\SendTo
c:\users\rzeygerman\Start Menu
c:\users\rzeygerman\Templates
c:\users\rzeygerman\Videos
c:\users\rzeygerman\AlphaFS-2.0.0\lib
c:\users\rzeygerman\AppData\Local
c:\users\rzeygerman\AppData\LocalLow
c:\users\rzeygerman\AppData\Roaming

When running this without Try/Catch,

it gives result above plus an error message

An error occurred while enumerating through a collection: (5) Access is denied: [\?\c:\users\rzeygerman\Application Data].
At line:1 char:63
- [Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories <<<< ($StartPath,"*", [System.IO.SearchOption]::AllDirectories)
  - CategoryInfo          : InvalidOperation: (Alphaleonis.Win...[System.String]:<Enumerate>d__3`1) [], RuntimeException
  - FullyQualifiedErrorId : BadEnumeration

**Comment by rzeygerman** [comment]
Basically, I am expecting to receive an identical result using 

 Try
 {$AllFilesArray=[Alphaleonis.Win32.Filesystem.Directory]::EnumerateDirectories($StartPath,"*", [System.IO.SearchOption]::AllDirectories)
 Foreach ($file in $AllFilesArray) { $file }
 }
 Catch {}

As I would using the code below:
$a=Get-ChildItem $StartPath -Recurse -Force -silentlycontinue | Where {$_.PSIsContainer}
Foreach ($Files in $a) {$Files.FullName}

**Comment by Yomodo** [comment]
The exception is typical to .NET, `[System.IO.Directory]::EnumerateXxx()` functions also suffers from this.

AlphaFS has a remedy for this, the function we're looking for is: `[Alphaleonis.Win32.Filesystem.Directory]::EnumerateFileSystemEntryInfos()`

This function supports: `DirectoryEnumerationOptions.ContinueOnException`
(http://alphafs.alphaleonis.com/doc/2.0/api/html/6354F8EE.htm)

Unfortunately, this functions makes use of .NET _generics_, which currently does not seem to be supported by PowerShell: http://stackoverflow.com/questions/4241985/calling-generic-static-method-in-powershell

I guess it can be done, but it's quite messy.
I will look at implementing overloaded methods, if possible.

**Comment by rzeygerman** [comment]
Thank you Jeffrey for all your help.
Looks like I need to find another way to do this.
I guess I can run the getchilditem  inside a try catch.
But how would I catch and assign LongPath to the running Array?

**Comment by Yomodo** [comment]
You can catch PATH TOO LONG errors using... AlphaFS :smile: 

Although it is usable from PowerShell, not all methods (like EnumerateFileSystemEntryInfos()) are suitable for PowerShell because of generics.

**Comment by Yomodo** [comment]
@rzeygerman Check this posting please: #157

**Comment by Yomodo** [comment]
Now possible in v2.2.
