### ISSUE TITLE
SetCurrentDirectory

### ISSUE THREAD

**Issue by martin-john-green** [alphaleonis/AlphaFS#145]
AlphaFS 2.0 (.Net 4.5) on Windows 7 and 8.1 called from PowerShell

The current working directory" used by AlphaFS seems to be different to the directory used by PowerShell (which is OK, that allows it to handle long path names).

However when calling SetCurrentDirectory() with a valid long absolute path an exception is thrown "Path is a zero-length string or contains only white space"

When calling SetCurrentDirectory() with a valid long relative path an exception is thrown "The specified path, file name or both are too long..."

**Comment by Yomodo** [comment]
In PowerShell `[Alphaleonis.Win32.Filesystem.Directory]::GetCurrentDirectory()`
`[System.Environment]::CurrentDirectory` and `[System.IO.Directory]::GetCurrentDirectory()` should all be equal since AlphaFS calls the .NET version internally.

Unfortunately, the Win22 API's for `GetCurrentDirectory()` and `SetCurrentDirectory()`
**do not** support the long path format.

As an alternative, avoid using relative paths and specify full paths.

**Comment by Yomodo** [comment]
_However when calling SetCurrentDirectory() with a valid long absolute path an exception is thrown "Path is a zero-length string or contains only white space"_

Could you show me an example of this?
Internally a regular (short) path is always constructed.

**Comment by martin-john-green** [comment]
The attached shows the two issues I mentioned in #145

PS I am brand new to GitHub!

CD C:\temp
SUBST X: /D
SUBST Y: /D
SUBST Z: /D

SUBST X: C:\temp
MKDIR    X:----01--------02--------03--------04--------05--------06--------07--------08--------09--------10----
SUBST Y: X:----01--------02--------03--------04--------05--------06--------07--------08--------09--------10----
MKDIR    Y:----11--------12--------13--------14--------15--------16--------17--------18--------19--------20----
SUBST Z: Y:----11--------12--------13--------14--------15--------16--------17--------18--------19--------20----
MKDIR    Z:----21--------22--------23--------24--------25--------26--------27--------28--------29--------30----

# AFS-SET-LOCATION.PS1

Import-Module AlphaFS

function afs-list-current-dir()
{
    $directory = "."
    $pattern = "*"
    $searchoptions = [System.IO.SearchOption]::TopDirectoryOnly # this directory only
    [Alphaleonis.Win32.Filesystem.Directory]::EnumerateFileSystemEntries($directory,$pattern,$searchoptions) |
    % { write-host $_ }
}

# to demonstrate this, create the following directories in C:\temp

$longpath1 =              "----01--------02--------03--------04--------05--------06--------07--------08--------09--------10----"
$longpath2 = "${longpath1}----11--------12--------13--------14--------15--------16--------17--------18--------19--------20----"
$longpath3 = "${longpath2}----21--------22--------23--------24--------25--------26--------27--------28--------29--------30----"

$longpath1
$longpath1.length

$longpath2
$longpath2.length

$longpath3
$longpath3.length

$rootdir = "C:\temp\long-pathnames"
[Alphaleonis.Win32.Filesystem.Directory]::SetCurrentDirectory( $rootdir )    # short, absolute

[Alphaleonis.Win32.Filesystem.Directory]::SetCurrentDirectory( $longpath1 )  # relative
write-host "Directory: (full paths) `r"
afs-list-current-dir
write-host "***`r"

[Alphaleonis.Win32.Filesystem.Directory]::SetCurrentDirectory( $longpath2 )  # long relative path
write-host "Directory: (full paths) `r"
afs-list-current-dir
write-host "***`r"

[Alphaleonis.Win32.Filesystem.Directory]::SetCurrentDirectory( $longpath3 )  # long relative path
write-host "Directory: (full paths) `r"
afs-list-current-dir
write-host "***`r"

$long_abs_path = "${rootdir}\${longpath3}"
$long_abs_path
$long_abs_path.length
[Alphaleonis.Win32.Filesystem.Directory]::SetCurrentDirectory( $long_abs_path )  # long absolute path 
write-host "Directory: (full paths) `r"
afs-list-current-dir
write-host "***`r"

**Comment by martin-john-green** [comment]
So the AlphaFS versions of these methods suffer from the same limitations as the .NET version?!

**Comment by Yomodo** [comment]
Unfortunately, yes. :disappointed:
