### ISSUE TITLE
Add overloaded methods to set Reparse Point Timestamp.

### ISSUE THREAD

**Issue by rstarkov** [alphaleonis/AlphaFS#147]
When presented with a path to a reparse point, all of the Set*Time methods modify the link target instead of the reparse point. This is consistent with the System.IO methods.

It would be great if there was a way to override this behaviour and provide an API to modify the reparse point timestamp instead.

Two use cases come to mind. One is that WinRAR is able to archive the contents of symlinked files, but only looks at the timestamp of the symlink to determine if it's changed. I'd like to update all symlink timestamps to match those of their targets, and this is currently not possible using AlphaFS. Two, is that I'd like to copy a directory as faithfully as possible, and this includes the corner case of copying symlink timestamps.

The change itself is trivial; it's a matter of passing ExtendedFileAttributes.OpenReparsePoint to CreateFileInternal inside SetFsoDateTimeInternal. But it's not entirely clear how to best expose that through the public API. Looks like an extra overload for each Set*Time method is required (as it looks like AlphaFS doesn't like using optional parameters in its API).

I'd love to submit a pull request, but it looks like the master branch is fairly old and there's a major refactoring happening on "develop", so I thought it's best to ask first.

**Comment by Yomodo** [comment]
You can submit a pull request on the develop branch.
Thanks for this feature!

**Comment by alphaleonis** [comment]
@rstarkov Yeah, the master branch is equal to the 2.0.1 release at this moment. The develop branch is for the next version 2.1. We are following the GitFlow branching model here, so no direct commits are made to the master branch.  A pull request for this feature should be made to the **develop** branch.

There is some more info [in the wiki](https://github.com/alphaleonis/AlphaFS/wiki/Contribution-Guidelines#for-contributors-with-write-access-to-the-repository).

**Comment by rstarkov** [comment]
Alright, so I'm thinking of doing it like this then: https://github.com/rstarkov/AlphaFS/commit/3ad814b438ca6e957941e5d56bcefa9fe284f107

Would appreciate a nod or something before I go ahead and do the same to the other 17 methods.

**Comment by Yomodo** [comment]
- I would like to see pathFormat as the last parameter.
- <see langword="true"/> instead of just true.
- modifyReparsePoint instead of modifyReparse
- A unit test.

@alphaleonis Looks good, right?
