### ISSUE TITLE
Suggestion: handling 'current directory'

### ISSUE THREAD

**Issue by martin-john-green** [alphaleonis/AlphaFS#152]
## Suggestion for AlphaFS handling of the 'current directory'

I realise that the "current" directory is a "global" concept used across many Windows/.NET functions. 

AlphaFS uses the global "current directory". It allows AlphaFS functions to resolve relative pathnames as expected and hence allows AlphaFS functions to be used alongside Windows/.NET functions

However, the Windows/.NET "current directory" is limited to MAX_PATH (260) characters 

This means that it is not possible to replace Windows/.NET functions that use the "current directory" with AlphaFS methods that process long pathnames correctly. This severely limits the usefulness of AlphaFS for re-engineering existing code.

I suggest the following approach:

```
AlphaFS has its' own CurrentDirectory and a flag indicating if it has been set.

When the AlphaFS module is loaded, the flag is false

While the flag is false, the Windows current directory is used to resolve partial paths

When AlphaFS SetCurrentDirectory() is called, 
    if the path is short enough for Windows, the Windows 'current directory' is set 
    if the path is longer than Windows can handle, the flag is set and the AlphaFS 'current directory' is set
```

When AlphaFS resolves a relative path, it uses the Windows "current directory" if (and only if) the AlphaFS method SetCurrentDirectory() has not been called, or has been called with a short path (flag is false) but uses the AphaFS "current directory" when SetCurrentDirectory() has been called with a long path (flag is true)

This would enable code to be re-engineered using AlphaFS methods as replacements for existing code even when it uses the 'current directory' and long paths 

I am currently recoding a large PowerShell script that does not cope properly with the long pathnames it encounters.
Being able to set the current directory to along path and have AlphaFS resolve relative paths correctly would be a big help.

HTH  ;-)

**Comment by Yomodo** [comment]
AlphaFS is **only** able to use long paths for a function when there is a Win32 API equivalent that supports long paths. For example: `System.IO.File.Copy()` uses the Win32 API `CopyFile()` while AlphaFS uses `CopyFileW()`.

For the `Directory.GetCurrentDirectory()` and `Directory.SetCurrentDirectory()` methods, there is no Win32 API with long path support which also effects AlphaFS.

For AlphaFS to support this would mean implementing our own native "Win32" versions of the `GetCurrentDirectory/SetCurrentDirectory` functions which is unlikely to happen.

Perhaps, as an alternative, you should re-think the design of your PowerShell script in regard to `Get/SetCurrentDirectory` dependancy?

Personally, I avoid using relative path names in C# apps and PowerShell scripts and always use full path names.

**Comment by alphaleonis** [comment]
I agree with @Yomodo here. Creating our own notion of "current directory" would be complicated and error prone and mostly confusing since we could never cover every scenario, which would mean you actually have two different _current directory_ settings depending on the function you're using.  It is a better idea to change you application to use full paths instead.

**Comment by martin-john-green** [comment]
I appreciate you reluctance to implement what would in effect give rise to two “current directories” 

I also prefer absolute path names, but when re-engineering existing code (not mine) it is not always economic to change a lot of code

I fail to see what value SetCurrentDirectory() and GetCurrentDirectory() add if they can’t handle long paths (which is one of the major “selling points” of AlphaFS)

Just get rid of them and tell people to use [System.IO.Directory] methods!

**Comment by Yomodo** [comment]
Even though `Get/SetCurrentDirectory()` do not support long paths, it is expected that these functions are available as AlphaFS claims to be a rewrite of several `System.IO` classes.

It is also kind of messy and confusing to switch between `[System.IO.Directory]` and `[Alphaleonis.Win32.Filesystem.Directory]`

Please don't shoot the coders.

**Comment by martin-john-green** [comment]
But these are not rewrites, they are wrappers that add no value

It is kind of messy to use some functions that do handle long paths and some that don’t!

Just keeping the coders honest

**Comment by Yomodo** [comment]
Some info.

After re-reading the MSDN docs on [`GetCurrentDirectory()`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364934%28v=vs.85%29.aspx) one could conclude that this function _should_ support long paths; MSDN neither confirms nor denies it, as opposed to `SetCurrentDirectory()`:
**The string must not exceed MAX_PATH characters, including the terminating null character.**

There exists a Unicode version of this function but that's no guarantee that it works.
For example: `SHGetFileInfoW()` fails when using long path notation with the Unicode version.

So: One _should_ be able to get the current directory of a long path, but can not set it manually.
Makes it hard to test also.
