### ISSUE TITLE
SetAccessControl

### ISSUE THREAD

**Issue by segfault-** [alphaleonis/AlphaFS#155]
was following this blog post:
http://blogs.technet.com/b/fieldcoding/archive/2014/12/05/ntfssecurity-tutorial-2-managing-ntfs-inheritance-and-using-privileges.aspx

specifically:
Set-NTFSOwner .\Data -Account 'NT AUTHORITY\SYSTEM'
Disable-NTFSAccessInheritance .\Data -RemoveInheritedAccessRules

when i try to set owner via AlphaFS:
try
                {

```
                Alphaleonis.Win32.Filesystem.Directory.SetAccessControl(path, ownerSecurity);
                // fails
            }
            catch (Exception ex)
            {
                  //works
                System.IO.Directory.SetAccessControl(path, ownerSecurity);
            }
```

what is going on here?

**Comment by Yomodo** [comment]
I don't know, you tell me :)
What exactly goes wrong?

**Comment by segfault-** [comment]
turns out it is working with the code below: 
                using (new Alphaleonis.Win32.Security.PrivilegeEnabler(Alphaleonis.Win32.Security.Privilege.Security, Alphaleonis.Win32.Security.Privilege.Audit, Alphaleonis.Win32.Security.Privilege.Restore, Alphaleonis.Win32.Security.Privilege.Backup, Alphaleonis.Win32.Security.Privilege.TakeOwnership))
                {
                    Alphaleonis.Win32.Filesystem.Directory.SetAccessControl(path, ownerSecurity, AccessControlSections.Owner);
                }
