### ISSUE TITLE
Add SuppressUnmanagedCodeSecurity attribute to [DllImport] tag.

### ISSUE THREAD

**Issue by KeyMetricSoft** [alphaleonis/AlphaFS#158]
I have a quick question for the original developers of this (excellent) library. Have you considered using the SuppressUnmanagedCodeSecurity attribute when p/invoking native methods?

More info here, if you're unfamiliar with the attribute:

http://blog.monitis.com/2012/05/29/improving-net-application-performance-part-16-code-access-security/

**Comment by alphaleonis** [comment]
No, I don't think that has been considered. Sounds interesting! I will have a look at that post and see if it would be applicable. Thanks for the tip!

**Comment by Yomodo** [comment]
I've played with this and could notice a performance increase in my app.
I've noticed no side effects, so it sounds safe to implement.
