### ISSUE TITLE
CreateSymbolicLink creates shortcut with no target

### ISSUE THREAD

**Issue by martin-john-green** [alphaleonis/AlphaFS#160]
It appears that CreateSymbolicLink() creates a shortcut (symlink) with no target

AlphaFS 2.0
Platforms: Windows Server 2008R2, Windows 7

PowerShell example: 

```
Import-Module AlphaFS

$shortcut_filename = "C:\temp\ptr"
$target_filepath   = "C:\temp\subdir"
$shortcut_type     = [Alphaleonis.Win32.Filesystem.SymbolicLinkTarget]::Directory

[Alphaleonis.Win32.Filesystem.File]::CreateSymbolicLink( "$shortcut_filename", "$target_filepath", $shortcut_type ) 

# Defect: shortcut created has no target directory
```

Using the same username (both with elevated privileges) 
the following DOS command works as expected

```
MKLINK /D "C:\temp\link" "c:\temp\target"
```

Maybe I am doing something wrong?

**Comment by Yomodo** [comment]
Unfortunately this is caused by using internal long path conversion.
The Windows API `CreateSymbolicLink()` does not support long paths.
