### ISSUE TITLE
Sequence naming of files

### ISSUE THREAD

**Issue by mwolfaardt** [alphaleonis/AlphaFS#161]
Hi, I would love to have a method that when you create a file,the file gets prefix with 01, and if the file exist 02 and so on. 
eg
create a file called file.txt
it will be called 01-file.txt or 01_file.txt
create another file called 01_file.txt and it gets renamed to 02_file.txt

I process a lot of files from email that has the same names and this would really help. 

If I get a list of files / paths that needs to be created, a method should be able to create it in sequence.

**Comment by Yomodo** [comment]
And how/when would this be applied from code?

**Comment by mwolfaardt** [comment]
If I get a list of files / paths that needs to be created, a method should be able to create it in sequence.

**Comment by Yomodo** [comment]
I'm still not sure if this is something to add to AlphaFS.
Although it sounds like a handy convenience method, its purpose will probably not/never satisfy everyone's need, but most of all, has little or nothing to do with long paths.

**Comment by alphaleonis** [comment]
I agree with @Yomodo. This is a simple method to create yourself on top of AlphaFS, and in a way that suits your particular needs.  And there is no good way to implement it so that it would suit everyones needs when it comes to the naming of files.  I suggest we close this one as WontFix.
