### ISSUE TITLE
Filtering out files to copy

### ISSUE THREAD

**Issue by alexaymonier** [alphaleonis/AlphaFS#163]
Hi Guys, 

Just getting to grips with this in PowerShell and liking it so far. We have a file share and need to copy certain departments data from the file share whilst excluding all other data. Looking at the following it looks like it copies all the child items from the Source.
# Set copy options.

PS C:> $copyOptions = [Alphaleonis.Win32.Filesystem.CopyOptions]::FailIfExists
# Set source and destination directories.

PS C:> $source = 'C:\sourceDir'
PS C:> $destination = 'C:\destinationDir'
# Copy directory recursively.

PS C:> [Alphaleonis.Win32.Filesystem.Directory]::Copy($source, $destination, $copyOptions)

I have found this which does filter using select-string but then cant work out how to use this in the copy.

 [Alphaleonis.Win32.Filesystem.Directory]::GetDirectories("\fileserver\tsprofiles$") | select-string -pattern "_abc"

Any help would be greatly appreciated.

Alex

**Comment by Yomodo** [comment]
I tested your syntax and it works fine.
You did notice that you're missing a backslash in here: `GetDirectories("\fileserver...`
