### ISSUE TITLE
File.Exists & Directory.Exists fail when path has leading space(s).

### ISSUE THREAD

**Issue by vincentparrett** [alphaleonis/AlphaFS#166]
This is a difference in behavior from System.IO. 

I looked a the code and it seems  like the solution would be to add a TrimStart option to GetFullPathOptions, I'm happy to create a pull request if this is an acceptable solution.

**Comment by Yomodo** [comment]
Could you supply a specific code-sample?

**Comment by vincentparrett** [comment]
Directory.Exists(" c:\test");

Will return false even when the directory does exist.

**Comment by Yomodo** [comment]
I should've asked more.

On my Win 8 x64, NET 3.5 - 4.5.1, both methods return `true`:
```
var spacePath = @"C:\ Test";
Console.WriteLine(System.IO.Directory.Exists(spacePath));
Console.WriteLine(Directory.Exists(spacePath));
```

However, in PowerShell both methods return `false`:
```
PS C:\> [IO.Directory]::Exists(' Test')
False
PS C:\> [Alphaleonis.Win32.Filesystem.Directory]::Exists(' Test')
False
```

**Comment by vincentparrett** [comment]
You are not testing the same thing. I am testing with

" C:\Test"

Note the space Before the C - with System.IO it returns true, AlphaFS returns false.

**Comment by Yomodo** [comment]
I can confirm the issue.

Adding a `TrimStart` to `GetFullPathOptions` would be a way to deal with this,
but it feels more like a workaround.
I need to investigate where it is that .NET trims the trailing space from a file path,
or where/why AlphaFS does not when it should.
