### ISSUE TITLE
Look the NTFS permissions of a folder

### ISSUE THREAD

**Issue by arnaudperfect** [alphaleonis/AlphaFS#167]
Hello,

I would like to look the NTFS permissions of a folder.
## I do that:

Add-type -Path D:\PowerShell\Script\AlphaFS.2.0.1\lib\net45\AlphaFS.dll
$Path = "\\Server\i$\Home\Folder-01"
$LongDirectory = [Alphaleonis.Win32.Filesystem.Path]::GetLongPath($Path) 
$FSObject = New-Object Alphaleonis.Win32.Filesystem.DirectoryInfo($LongDirectory)
$ItemACL = $FSObject.GetAccessControl("Access")
$ItemACL.GetAccessRules($true, $true, [System.Security.Principal.SecurityIdentifier])
## The result is:

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : S-1-5-32-544
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : Modify, Synchronize
AccessControlType : Allow
IdentityReference : S-1-5-21-3322481332-1229247672-3819975754-1018
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : Modify, Synchronize
AccessControlType : Allow
IdentityReference : S-1-5-21-3322481332-1229247672-3819975754-1106
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : Modify, Synchronize
AccessControlType : Allow
IdentityReference : S-1-5-21-3322481332-1229247672-3819975754-1107
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : Modify, Synchronize
AccessControlType : Allow
IdentityReference : S-1-5-21-3322481332-1229247672-3819975754-1108
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

I wish I had credentials (The user account or user group)
Is this possible with AlphaFS? How to do?

Thank you

**Comment by Yomodo** [comment]
I think you need this:

[How do I get the display name for an IdentityReference object?](http://stackoverflow.com/questions/7005761/how-do-i-get-the-display-name-for-an-identityreference-object)

**Comment by arnaudperfect** [comment]
Hello,

Thank you for your return.

I tried to use the function "System.Security.Principal.SecurityIdentifier()" and " Translate()", but it does not work with this local accounts on remote servers.

$LongDirectory = [Alphaleonis.Win32.Filesystem.Path]::GetLongPath($Path)
$ItemACL = [Alphaleonis.Win32.Filesystem.Directory]::GetAccessControl($LongDirectory)
$ItemACL.GetAccessRules($true, $true, [System.Security.Principal.SecurityIdentifier])| ForEach-Object{
$objSID = New-Object System.Security.Principal.SecurityIdentifier($_.IdentityReference.value)
$Name = ( $objSID.Translate([System.Security.Principal.NTAccount]) ).Value
$Name
}

An example on Windows: a folder on the network where the local groups are configured. Windows resolves correctly name the groups :

http://www.developpez.net/forums/attachments/p176938d1430838269/general-developpement/programmation-systeme/windows/scripts-batch/permissions-ntfs-repertoires/titre2.jpg/

The same via PowerShell from AlphaFS and Get-ACL :
http://www.developpez.net/forums/attachments/p176939d1430838333/general-developpement/programmation-systeme/windows/scripts-batch/permissions-ntfs-repertoires/titre.jpg/

Natively functions AlphaFS and GET-ACL do not allow to get the display name for an IdentityReference object. The function "System.Security.Principal.SecurityIdentifier()" and " Translate()", it does not work with this local accounts on remote servers.

I use this method, but very consumer execution time, and not robust because it uses WMI :

Get-WmiObject -Class Win32_Group -ComputerName “SERVER” -Filter "DOMAIN='SERVER' AND SID='S-1-5-21-34234453-4345543-456443-4345'" | Select Caption, SID

**Comment by Yomodo** [comment]
Perhaps this one can be of help, it also uses AlphaFS:

File System Security PowerShell Module 3.2.3
https://gallery.technet.microsoft.com/scriptcenter/1abd77a5-9c0b-4a2b-acef-90dbb2b84e85
