### ISSUE TITLE
Error on File.Open with access-mode Append?

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#168]
Hi,
I get an error, if opening a file in append mode using:
File.Open(path, FileMode.Append, FileAccess.Write, FileShare.Read);
The same call to the .Net-API works as expected. Is this a bug?
The error is:
System.IO.IOException was unhandled by user code
  HResult=87
  Message=(87) Falscher Parameter: [\?\E:\Backup\2015-05-10_19.10\backup_2015-05-10_19_10_13.log]
  Source=AlphaFS
  StackTrace:
       bei Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
       bei Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, String readPath)
       bei Alphaleonis.Win32.Filesystem.File.CreateFileInternal(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
       bei Alphaleonis.Win32.Filesystem.File.OpenInternal(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileAccess access, FileShare share, ExtendedFileAttributes attributes, PathFormat pathFormat)
       bei Alphaleonis.Win32.Filesystem.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
       bei Lupinho.Net.HardlinkBackup.Engine.IO.Alpha.AlphaFileSystemAccess.Open(String path, FileMode fileMode, FileAccess fileAccess, FileShare share) in d:\Benutzer\Lupinho\Workspaces\Visual Studio\Projects\HardlinkBackup\Lupinho.Net.HardlinkBackup.Engine\IO\Alpha\AlphaFileSystemAccess.cs:Zeile 422.
  InnerException:

**Comment by Yomodo** [comment]
Does it make a difference if you remove: `\?\`E:\Backup\...  ?

**Comment by Yomodo** [comment]
Confirmed.

**Comment by Yomodo** [comment]
@Lupinho Could you please check if #116 is still an issue?

**Comment by Lupinho** [comment]
Yes it is - unfortunately. Same error occurres with latest build. I try to copy from a shadow copy asynchroneously (which is a write protecteted volume).

**Comment by Yomodo** [comment]
Could i duplicate your issue by using your tool:HardlinkBackup and try a `File.Append()` ?

**Comment by dpfl** [comment]
I have the same issue and can replicate it like this
`new FileInfo(@"textfile.txt").Open(FileMode.Append, FileAccess.Write, FileShare.ReadWrite);`
I am on v2.0.1

**Comment by Yomodo** [comment]
@Lupinho @dpfl Could you please test again with the latest development build?

**Comment by Yomodo** [comment]
I can not replicate/confirm the issue.
