### ISSUE TITLE
Getting CompressedSize and SizeOnDisk

### ISSUE THREAD

**Issue by Jan1503** [alphaleonis/AlphaFS#170]
Hi there!

I also have the problem with these stupid path-too-long exceptions and would like to switch to your library.

I need to scan the shares on various file-servers and enumerate it's sizes for billing purposes.
For this I need to get the "real" size-on-disk and not the size of the file itself.

Here's some snippet in vb.net which I'm currently using to do this:

For Each file In extendedShare.Root.EnumerateFiles
                Try
                    Dim fileSize = file.Length
                    overallSize += CLng(fileSize)

```
                If file.Attributes = (file.Attributes Or FileAttributes.Compressed) Then
                    Dim hosize As UInteger = 0
                    Dim losize = Win32.GetCompressedFileSizeW(file.FullName, hosize)

                    sizeOnDisk = CLng(hosize) << 32 Or losize
                Else
                    sizeOnDisk = CLng(Math.Ceiling(fileSize / extendedShare.BlockSize) * extendedShare.BlockSize)
                End If

                overallSizeOnDisk += sizeOnDisk
            Catch ex As Exception
                Log.WarnException("Server: " & extendedShare.Server & ", File: " & file.FullName & ", Error.", ex)
                'Ignore unreadable files.
            End Try
        Next
```

Is there any native support for this in your library or do I still need to use my code?
It's because to calculate the size-on-disk you need to get the blocksize of the volume via WMI which is slow and needs another port (rpc 135 tcp) to be opened.

Thanks and regards,
Jan

**Comment by Yomodo** [comment]
Hi,  there's the implementation of [File.GetCompressedSize()](http://alphafs.alphaleonis.com/doc/2.0/api/html/B2A9FCCA.htm) method.
To get a volume's cluster size etc, you can use the [DiskSpaceInfo()](http://alphafs.alphaleonis.com/doc/2.0/api/html/C720ACA5.htm) class.

**Comment by Jan1503** [comment]
Thanks for your reply.
Will try that!
Regards,
Jan
