### ISSUE TITLE
How to avoid deadlocks because of junction points

### ISSUE THREAD

**Issue by Jan1503** [alphaleonis/AlphaFS#171]
Hi!

I'm using AlphaFS to scan a bunch of fileservers for shares and report it's sizes for billing purposes.

Now over the weekend my service runs into an endless loop because of a juntion point under users profiles "application data". See here: http://answers.microsoft.com/en-us/windows/forum/windows_7-files/windows-7-infinite-loop-while-using-robocopy/20f32f0c-4cb9-4125-923d-6a57e4d27232
or here: http://answers.microsoft.com/en-us/windows/forum/windows_7-files/application-data-circular-reference/746342b2-0119-4461-a3d7-610c435a6715

Also check my image attached.

My question is how to avoid this loop in the best way? Check every directory or file if it's a symbolic link? Or could I disable this behaviour globally?

Thanks for help!!
Regards,
Jan
![infinite loop](https://cloud.githubusercontent.com/assets/10504259/8029823/9ba2d022-0dc1-11e5-9102-2cbcb0e58b5b.PNG)

**Comment by Yomodo** [comment]
Hi Jan,
The AlphaFS implementation of `DirectoryInfo` and `FileInfo` both contain an additional property: [EntryInfo](http://alphafs.alphaleonis.com/doc/2.0/api/html/7D97CBAE.htm) which might help you out: `IsMountPoint`, `IsReparsePoint`, `IsSymbolicLink`

FileSystemEntryInfo instances can also be returned by using method [Directory.EnumerateFileSystemEntryInfos()](http://alphafs.alphaleonis.com/doc/2.0/api/html/3235A655.htm), which might even be a bit faster.

**Comment by Jan1503** [comment]
Thanks Yomodo,

but what happens, if I use the recursive search function of the framework to get my files since it's easier...

```
For Each di In shareInfo.Root.EnumerateDirectories("*").Where(Function(a) a.EntryInfo.IsMountPoint = False And a.EntryInfo.IsReparsePoint = False And a.EntryInfo.IsSymbolicLink = False)
                Try
                    For Each file In di.EnumerateFiles("*", SearchOption.AllDirectories).Where(Function(a) a.EntryInfo.IsMountPoint = False And a.EntryInfo.IsReparsePoint = False And a.EntryInfo.IsSymbolicLink = False)
                        Try
                            Dim fileSize = file.Length
                            overallSize += CLng(fileSize)

                            If file.Attributes = (file.Attributes Or FileAttributes.Compressed) Then
                                Dim compSize = Alphaleonis.Win32.Filesystem.File.GetCompressedSize(file.FullName)

                                sizeOnDisk = compSize
                            Else
                                sizeOnDisk = CLng(Math.Ceiling(fileSize / shareInfo.BlockSize) * shareInfo.BlockSize)
                            End If

                            overallSizeOnDisk += sizeOnDisk
                        Catch ex As Exception
                            Log.WarnException("Server: " & shareInfo.ServerName & ", File: " & file.FullName & ", Error.", ex)
                            'Ignore unreadable files.
                        End Try
                    Next
                Catch ex As Exception
                    Log.WarnException("Server: " & shareInfo.ServerName & ", Directory: " & di.FullName & ", Error.", ex)
                    'Ignore unreadable directories.
                End Try
```

How to handle it there?
Haven't tested the above exclusions yet but would assume they're not working on subdirectories.

**Comment by Yomodo** [comment]
Sorry, I'm not sure what you mean.
It should be possible to replace `EnumerateDirectories()` and `EnumerateFiles()` with `EnumerateFileSystemEntryInfos()`

**Comment by Jan1503** [comment]
Hi!
As I said, I need to get the overall size of any shares of my fileservers. As there is no built-in method to get the overall size, I need to recursively step thru the directories and get the file's length.
I'm not sure, if my current code is the fastest one, but it works well. But I'm afraid it will fail if some sub-directory is a junction point. I added the exclusion at the top-level directory but can't set it on any subdirectory without writing my own recursive function.

Or maybe I'm not sure what you try me to tell :)

**Comment by Yomodo** [comment]
Just to be clear, did the addition of: `.Where(Function(a) a.EntryInfo.IsMountPoint = False And a.EntryInfo.IsReparsePoint = False And a.EntryInfo.IsSymbolicLink = False)`
helped in solving your issue?

**Comment by Jan1503** [comment]
Hi!
Sorry for my late reply.
I haven't tried it today cause I can't run it during normal work hours due to the load it causes.
But from a few test's I can see it's significantly slower with these exceptions. Will do further tests tomorrow. Currently I'm using 2 threads per server to avoid hdd overloading.

Maybe u know of any other method to efficiently enumerate folder-sizes? I'm not happy with this solution at all. It works, but it's slow...

Edit: just found this: http://stackoverflow.com/questions/2979432/directory-file-size-calculation-how-to-make-it-faster
Will try it tomorrow...

**Comment by Jan1503** [comment]
Ok, just a quick update. Above exclusions didn't work on subdirectories just as expected. Only the top-level dirs are checked. Will have to implement my own recursive function. May be this could be an enhancement in future versions?

**Comment by Jan1503** [comment]
Just looked at your comment about EnumerateFileSystemEntryInfos() again. It's worth a try using the flags to return files only and to skip reparse points.

**Comment by Yomodo** [comment]
Indeed, don't forget to also add `Recursive`.

**Comment by Jan1503** [comment]
Sorry for my late reply. Everything works as expected now.
