### ISSUE TITLE
Error on EnumerateAlternateDataStreams.MoveNext on shadow copies

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#173]
I'd like to get alternative datastreams for files of a volume shadow copy. So path starts like this: "\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy89\"
Then I get an error like this:
System.IO.IOException: (123) Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
   bei Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   bei Alphaleonis.Win32.Filesystem.File.<EnumerateAlternateDataStreamsCore>d__8.MoveNext()

Can you help me?

**Comment by Yomodo** [comment]
The alternative datastream methods do not work with/for Shadow copies.
