### ISSUE TITLE
Problem with operators

### ISSUE THREAD

**Issue by frozenshadow** [alphaleonis/AlphaFS#174]
This is the first time I use AlphaFS. I have read the documentation over and over again but can’t figure out how to solve this problem. The original piece of code:

``` C#
if ((System.IO.File.GetAttributes(filename) & FileAttributes.Hidden) != FileAttributes.Hidden)
                    {
                        foundFiles.Add(filename); // If the file is NOT hidden, add them to the list
                    }
```

When ‘converting’ this to AlphaFS it gives me the following error:

```
Operator '&' cannot be applied to operands of type 'System.IO.FileAttributes' and 'Alphaleonis.Win32.Filesystem.ExtendedFileAttributes'
```

And the converted code:

``` C#
if ((Alphaleonis.Win32.Filesystem.File.GetAttributes(filename) & Alphaleonis.Win32.Filesystem.ExtendedFileAttributes.Hidden) != Alphaleonis.Win32.Filesystem.ExtendedFileAttributes.Hidden)
                    {
                        foundFiles.Add(filename); // If the file is NOT hidden, add them to the list
                    }
```

I’m kind of stuck… can someone help me?
thanks in advance :)

**Comment by Yomodo** [comment]
Use casting, this should work:

```
if ((Alphaleonis.Win32.Filesystem.File.GetAttributes(filename) & (FileAttributes) Alphaleonis.Win32.Filesystem.ExtendedFileAttributes.Hidden) != (FileAttributes) Alphaleonis.Win32.Filesystem.ExtendedFileAttributes.Hidden)
         {
            foundFiles.Add(filename); // If the file is NOT hidden, add them to the list
         }
```

or, better:

```
if ((Alphaleonis.Win32.Filesystem.File.GetAttributes(fi.FullName) & FileAttributes.ReadOnly) != 0)
         {

         }
```

**Comment by frozenshadow** [comment]
Thank you very much Yomodo!
I never thought about that. I’ll try this later today.

**Comment by frozenshadow** [comment]
It works (as expected) flawlessly. It really helped me get my project lifted off the ground. Again thank you for your support!

Wouldn’t it be great to have some examples on the documentation page? I personally really tend to look at those to understand the code underneath. Maybe even some MSDN examples converted to AlphaFS… Just an idea ;)

**Comment by Yomodo** [comment]
:) Glad you have it working!

Take a peek here: http://alphafs.alphaleonis.com/
Although, there are no code samples, but well documented AlphaFS members.

Also, the unit-tests are good examples.
