### ISSUE TITLE
Use Regex as searchPattern to exclude Files/Folders

### ISSUE THREAD

**Issue by windischb** [alphaleonis/AlphaFS#177]
Hi!

Currently i have to enumerate over a bunch of Fileserver shares to generate a Report of all Users who have "Full Control" Permissions...
On this Fileserver there is DFS enabled.
DFS generates a Folder for replication and conflicts/errors.
It would be great if we could use Regex as searchPattern in "EnumerateFileSystemEntryInfos" to exclude such directories!
Or is there any other solution for EXCLUDE folders LIKE "_DfsrPrivate_"?
Any Ideas???

Many Thanks
Bernhard

**Comment by Yomodo** [comment]
Hi,
Unfortunately there's no RegEx searching available.
