### ISSUE TITLE
Network connects methods hangs in Windows service when credentials fail

### ISSUE THREAD

**Issue by brutaldev** [alphaleonis/AlphaFS#180]
If the credentials provided fail when using something like new `new Alphaleonis.Win32.Network.DriveConnection()` or `Host.ConnectTo()` then the code will always prompt with a dialog asking for the credentials. This is fine for applications with a user interface, but if the provided credentials (say from a config file) fail in a Windows service application, then the prompt ends up hanging the service process.

Line [445](https://github.com/alphaleonis/AlphaFS/blob/49e666a8f2/AlphaFS%2FNetwork%2FHost%20Class%2FConnect.cs#L445) in the Host class sets the default connection option to `NativeMethods.Connect.Interactive` which should not be the case when running as a service.

Ideally this default should only be set if `Environment.UserInteractive` is `true`, otherwise a more sensible default when `Environment.UserInteractive` is `false` would probably be `NativeMethods.Connect.None`. To be safe, `arguments.Prompt` could also be negated when it is not interactive but ideally the developer should be passing in `Environment.UserInteractive` as the argument for `prompt` in the various methods.

**Comment by Yomodo** [comment]
Thanks for reporting.

**Comment by brutaldev** [comment]
No problem, I integrated AlphaFS into a pretty massive, file system and network share focused application and picked up some of these issues. Easy enough to fix/workaround and I was going to make pull requests for you guys if no-one picked it up.

Thanks for the great library, I recommend it to everyone that needs to do anything significant on the file system in .NET.

**Comment by Yomodo** [comment]
It seems that interaction with the desktop has been disabled in Windows Vista and beyond,
so I ignored the use of `Environment.UserInteractive`: [Interactive Services](https://msdn.microsoft.com/en-us/library/ms683502%28VS.85%29.aspx)

Instead, `NativeMethods.Connect.None` is now the default and `NativeMethods.Connect.Interactive` is only applied if _Prompt_ is `true`.

**Comment by Yomodo** [comment]
Also, could you be bothered to share your AlphaFS experience @ #143

**Comment by brutaldev** [comment]
That's correct, so in Windows services from Vista up that are not interactive, the value for `Environment.UserInteractive` will always be `false` and it's `true` in desktop applications. Even if the service has desktop interaction enabled, the prompt will work but just sit there if no-one is logged in.

I agree with having `NativeMethods.Connect.None` as the default, it's much safer and predictable.
