### ISSUE TITLE
Get right access on network share

### ISSUE THREAD

**Issue by arnaudperfect** [alphaleonis/AlphaFS#187]
Hello,

Is it possible, with your API, to get right access on network share ? (everyone, etc)
If so, how?

I get to list the network share on a remote server ([Alphaleonis.Win32.Network.Host] :: EnumerateShares ("\SRV001", True) $ | FT), but no access rights on share.

Best Regard,
Arnaud

**Comment by Yomodo** [comment]
I think this is what you need: http://alphafs.alphaleonis.com/doc/2.0/api/html/1B7C2B56.htm
ShareInfo class
