### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by thomaslevesque** [alphaleonis/AlphaFS#207]
Hi,

I was wondering about the roadmap for AlphaFS ; is there a new release coming soon?. I see there are lots of changes since 2.0.1 (which was released 6 months ago), and there hasn't been any new release since then. Would it be possible to make more frequent maintenance releases to address known bugs? It would be really helpful. Right now if I need a bugfix for my app I need to build AlphaFS from my own fork, I can't get it from NuGet until the fix is included in a release.

**Comment by brutaldev** [comment]
+1
I'm also performing custom builds and releasing 2.0.2 for my projects eagerly awaiting the official 2.1.

**Comment by alphaleonis** [comment]
@Yomodo I haven't been following the recent development very closely (or at all). Where do we stand on the release-front? All check-ins since 2.0.1 seems to have been done in _develop_, meaning that these should be feature enhancements rather than bugfixes?  But apparently there must be bugfixes there as well, judging by the comments above? So where do we stand on releasing a 2.1 as of now?

**Comment by Yomodo** [comment]
Focusing on 2.1, a lot of (reported) bugs have been fixed.
Only the unit tests have not been split yet.

I have only checked-in on the develop branch, did not do anything on the master branch.
So, as far as I'm concerned, I think we're good to go for a next release.

**Comment by alphaleonis** [comment]
Alright. I'm a bit short on time at the moment, but perhaps we can get something released next week? (Or possibly on Sunday), if there are no more pending work-items that should be addressed before the 2.1 release?

**Comment by Yomodo** [comment]
I will try to fix the remaining/open issues for the 2.1 release.

**Comment by alphaleonis** [comment]
@Yomodo Great. Let me know if you need any assistance... A bit short on time as I said, but I'll try to help out where I can.

**Comment by thomaslevesque** [comment]
Thanks guys for your replies!

**Comment by Yomodo** [comment]
@thomaslevesque I apologize for not keeping my word.
Will get back to this, ASAP.

**Comment by NoMoreFood** [comment]
Good to see there's some activity on this project.  Eagerly awaiting the next release :-)

**Comment by CyberSinh** [comment]
@Yomodo @alphaleonis Can we expect a new release of AlphaFS (2.1) soon ? Thanks.

**Comment by Yomodo** [comment]
Hi, kind hard to say..
There are still some bugs to fix but at the moment, and I, **unfortunately**, have little time at the moment for AlphaFS.

**Comment by alphaleonis** [comment]
This has been long overdue. Guess both me and @Yomodo got too tied up with other things in life to get the release out like we had hoped. But we are aiming for a release in October 2016 now anyway, and the plan is to get bugfix releases out more often after that.

**Comment by thomaslevesque** [comment]
@alphaleonis thanks for the update, that's very good news!

**Comment by Yomodo** [comment]
I guess this one can also be closed?
