### ISSUE TITLE
Could not delete Junction

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#210]
I try to delete a junction point. This gives me an error "wrong parameter". I guess, the reparse point data should be removed first; but this should be done by Directory.Delete transparently?!

**Comment by rstarkov** [comment]
In fact, Directory.Delete tries to do this transparently, and it's _that_ which fails. Commenting out the error check after `Volume.DeleteVolumeMountPointCore` makes junction deletes work correctly (at least in the simple case).

**Comment by Yomodo** [comment]
With the current development build (2.1.0.0) I'm not able to replicate this error.
Here's what I did:

`C:\>md Test`
`C:\>mountvol.exe C:\test \\?\Volume{471843fd-0000-0000-0000-501f00000000}\`

And finally remove the folder: `Alphaleonis.Win32.Filesystem.Directory.Delete(@"C:\Test");`
No errors/exceptions, am I missing something?
