### ISSUE TITLE
Using AlphaFS in VB.net with Long Filenames

### ISSUE THREAD

**Issue by sonypsx** [alphaleonis/AlphaFS#211]
Hello,

just found your wonderful gold nugget AlphaFS. The Description and Documentation sounds awesome. But i got stuck by a "simple" file move operation. Language used: VB.net (2013)

I tried the following: 
Alphaleonis.Win32.Filesystem.File.Move("c:\x\test1.txt", "c:\x\test2.txt")

Which works flawless, right after that i tried:

Alphaleonis.Win32.Filesystem.File.Move("c:\x\test2.txt", "c:\x\0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt")

The Exception looks like this: (i have translated it because i'm using a german version:
An Exception Error has occured of type "System.IO.IOException" in AlphaFS.dll Additional Info: (123) The syntax for the filename, directoryname or volumelabel is wrong: [\?\c:\x\0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt]

If you wonder about the length, its about 409 chars so that shouldn't be a problem.

Can you tell what i'm doing wrong? Yes the drive is NTFS formatted and a have full acess rights on this directory!

Thanks for you help!

**Comment by alphaleonis** [comment]
The maximum length of an individual component in a path is 255 characters if I remember correctly. The post at http://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista seems to verify this.

**Comment by sonypsx** [comment]
THAT was the point "EACH individual component"  i tought i could archived 1000 characters long filenames only - without the path of course. So i'm stuck with that limitation on NTFS.
Thanks for confirmation!

**Comment by alphaleonis** [comment]
You're welcome!
