### ISSUE TITLE
Howto Get-Filehash

### ISSUE THREAD

**Issue by bjoe2k4** [alphaleonis/AlphaFS#214]
Hi, 

i am trying to replace the following command with an AlphaFS analogue:

`$chash = (gi -LiteralPath "$fullpathfilename" -force | get-filehash).Hash`

Is that even possible?

Regards

**Comment by Yomodo** [comment]
Unfortunately, AlphaFS does not support this.

**Comment by bjoe2k4** [comment]
Thanks, then i will have to look out for something else.

**Comment by bjoe2k4** [comment]
Thanks! Looking forward to see v2.1 soon!

**Comment by Yomodo** [comment]
You know you can already download the develop version. compile and use that, right?

**Comment by bjoe2k4** [comment]
Right, just installed 8GB of Windows Compiler (MS VS2015 CE) to compile a 256K dll. Will test new features tomorrow :-)
