### ISSUE TITLE
Howto - Set file attribute

### ISSUE THREAD

**Issue by Zuldan** [alphaleonis/AlphaFS#215]
I've written a PowerShell script that uses AlphaFS to search for files with a temporary attribute. Most of these files exist in directories with paths longer than 260 chars. I'm not exactly sure how to get AlphaFS to remove the temporary attribute for files in very long paths. I'm guessing I have to use "ExtendedFileAttributes" in some way. I would be most grateful for any tips on how to do this.

PS: thank for writing AlphaFS. Working with files in Powershell became a lot easier for me.

**Comment by Zuldan** [comment]
Silly me, I was looking in the wrong section of the API doco.

Add Temporary

Remove Temporary

**Comment by boxingsurfer** [comment]
hello friend

can you explain a bit more about where the API docs contain this info
I cant find any reference on specific ways to add temporary or remove temporary attributes

help appreciated

**Comment by Yomodo** [comment]
Hi, I think this one might do it:
http://stackoverflow.com/questions/7399611/how-to-remove-a-single-attribute-e-g-readonly-from-a-file

**Comment by boxingsurfer** [comment]
yes I came across that one myself but the original post seemed to imply some methods within AlphFS for doing it. The example provided isn't easy to translate into powershell

I solved this myself by using the following techniques. I will give examples:

**Check the existence of specific attribute bits using BAND logic:**
- get attributes of a file ($file contains the full file path):
  `$attr = [Alphaleonis.Win32.Filesystem.File]::GetFileSystemEntryInfo($file).Attributes`
- test whether if a particular attribute bit is set (lots of examples)

```
IF (($attr -band  [System.IO.FileAttributes]::Temporary) -eq [System.IO.FileAttributes]::Temporary)
IF (($attr -band  [System.IO.FileAttributes]::Hidden) -eq [System.IO.FileAttributes]::Hidden)
IF (($attr -band  [System.IO.FileAttributes]::System) -eq [System.IO.FileAttributes]::System)
IF (($attr -band  [System.IO.FileAttributes]::Directory) -eq [System.IO.FileAttributes]::Directory)
IF (($attr -band  [System.IO.FileAttributes]::Archive) -eq [System.IO.FileAttributes]::Archive)
IF (($attr -band  [System.IO.FileAttributes]::Device) -eq [System.IO.FileAttributes]::Device)
```

**Change a specific attribute bit using BXOR logic:**
- flip the attribute bit in a new value, from the old value (e.g. the temporary bit). You can do this the same with any bit using the system io fileattributes 
  `$newAttr = $attr -bxor [System.IO.FileAttributes]::Temporary`
- set the new attribute back on the original file 
  `[Alphaleonis.Win32.Filesystem.File]::SetAttributes($file,$newAttr)`

not too brilliant, but its the most elegant solution I could come up with. 

I'd be really glad if someone could show me a better or more simple or elegant way

If not, then I hope this can help someone else
