### ISSUE TITLE
Directory.Exists returns false if dirspec is long and root, such as \\?\c:\

### ISSUE THREAD

**Issue by warrenlbrown** [alphaleonis/AlphaFS#216]
If the spec is c:\ it returns true.

**Comment by Yomodo** [comment]
With the latest develop build:

`False: Console.WriteLine(System.IO.Directory.Exists(@"\\?\c:\"));`
`False: Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\"));`

`True: Console.WriteLine(System.IO.Directory.Exists(@"c:\"));`
`True: Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"c:\"));`
