### ISSUE TITLE
File.Replace() raises an exception

### ISSUE THREAD

**Issue by pinocchio85** [alphaleonis/AlphaFS#217]
The "Find.Replace()" method raises an "ArgumentNullException" when you pass null to the "destinationBackupFileName" parameter, e.g.:

`File.Replace(@"D:\Test1.txt", @"D:\Test2.txt", null);`

According to the documentation, you can pass null to the destinationBackupFileName parameter if you do not want to create a backup of the file being replaced.

**Comment by Yomodo** [comment]
@pinocchio85 It think the issue has been resolved. Care to test it?
