### ISSUE TITLE
Volume.GetVolumeInfo() fails for global root paths

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#218]
If you call Volume.getVolumeInfo() with a global root volume path (e.g. a shadow copy path) the call fails with an ArgumentException.

**Comment by Yomodo** [comment]
Could you please specify the/a path that you use?

**Comment by Lupinho** [comment]
You can take any shadow-copy path (as said above). I can't tell you a valid shadow copy path on your machine... E.g.: type "vssadmin list shadows" in a administrative console, this lists all shadow copies on your machine. Then you can take this path and pass it to VolumeInfo. On my machine "\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy37" is a valid shadow copy. 
A call to Volume.GetVolumeInfo("\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy37") would result in an ArgumentException thrown in the VolumeInfo(string)-constructor. If you just remove the path checks for this paths from the constructor, the result is a valid and filled VolumeInfo-instance. So, just the path check needs to be adjusted for global-root-paths.
