### ISSUE TITLE
DirectoryInfo not working with junctions/reparse points

### ISSUE THREAD

**Issue by mcschorr** [alphaleonis/AlphaFS#220]
Hello,

If I try to access the folders of a NTFS junction/reparse points like:

\??\Volume{17426ae7-0000-0000-0000-100000000000}\

which is mapped to "C:\folder", an exception is thrown that it can't find the folder in the OS.

For example:

```
var directoryInfo = new Alphaleonis.Win32.Filesystem.DirectoryInfo("C:\folder");
if (directoryInfo.GetDirectories().Length > 0)
{...}
```

Method "GetDirectories()" throws the exception -> Can't find folder!

Is it possible to work with junctions with AlphaFS or is this an issue?

Hope you can help!

Thank you in advance!

**Comment by Yomodo** [comment]
Hi, do you also get an exception when using DirectoryInfo from System.IO ?

**Comment by Yomodo** [comment]
Unfortunately I can not replicate this error.
