### ISSUE TITLE
ReFS Directory.Compress 

### ISSUE THREAD

**Issue by mikequinlan** [alphaleonis/AlphaFS#222]
I've begun testing AlphaFS on a ReFS (https://msdn.microsoft.com/en-us/library/windows/desktop/hh848060(v=vs.85).aspx) volume on Windows 10.

The test AlphaFS_Compress fails because ReFS doesn't support compression. When Directory.Compress is called for a folder on a ReFS volume it throws an IO Exception, which should be the expected response. The test instead expects the compress file attribute to be set which is not.

This also affects the AlphaFS_GetSize test because FileInfo.Compress throws an IO Exception when the file is on a ReFS volume.

These are only errors in the tests. The code operates correctly. I am not sure how to fix this or even if it is worth bothering about but I wanted to let you know.

**Comment by Yomodo** [comment]
Thanks for reporting. Unit tests are still one of our "issues" to resolve.

**Comment by Yomodo** [comment]
Question: Does ReFS also suffer from PathTooLong?

**Comment by mikequinlan** [comment]
Yomodo -- the PathTooLong error is from Windows, not the file system. NTFS and ReFS both support long paths but the WIndows API doesn't (that is how AlphaFS works).

There might be a glimmer of hope on the horizon though. A number of sites have reported a new setting in the latest Windows 10 builds that lets applications support long paths. [Microsoft Removes 260-Character Path Length Limit](https://www.reddit.com/r/technology/comments/4lkoe4/microsoft_removes_260character_path_length_limit/d3oemxd) is one discussion. You need to include a manifest in your application in addition to the registry/group policy  change. I (and others) have tested this and it doesn't seem to be actually implemented yet.

It seems to be something planned for Windows Server 2016 and WIndows 10. At this point it doesn't affect .net -- the .net framework still checks for the old limits and ignores the longPathAware manifest setting.

**Comment by mikequinlan** [comment]
Yomodo --

.NET 4.6.2 now supports paths that begin with the //?/ prefix.

https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/

I've run a simple test and it seems to work. I haven't tested anything complex though.

**Comment by Yomodo** [comment]
Thank you for reporting! Yeah.. that was bound to happen of course.
