### ISSUE TITLE
Bug : DACL returned by Directory.GetAccessControl(path);

### ISSUE THREAD

**Issue by AlexLaroche** [alphaleonis/AlphaFS#224]
GetAccessRules() isn't return the good FileSystemRights value.

In the exemple below, the function return "Read and Execute" where the good filesystem right is  "List folder content".

P.S.: Sorry, for the french screen capture.

```
try
{
    DirectorySecurity ds = Directory.GetAccessControl(path);
    SecurityIdentifier owner = ds.GetOwner(typeof(SecurityIdentifier)) as SecurityIdentifier;
    SecurityIdentifier primaryGroup = ds.GetGroup(typeof(SecurityIdentifier)) as SecurityIdentifier;
    AuthorizationRuleCollection dacl = ds.GetAccessRules(true, true, typeof(SecurityIdentifier));
    si = new SecurityDescriptor(path, owner.ToString(), primaryGroup.ToString());

    foreach (FileSystemAccessRule rule in dacl)
    {
        InheritanceFlags inheritance = rule.InheritanceFlags;
        bool inherited = rule.IsInherited;
        PropagationFlags propagation = rule.PropagationFlags;
        SecurityIdentifier sid = rule.IdentityReference as SecurityIdentifier;
        FileSystemRights rights = rule.FileSystemRights;

        ACE ace = new ACE(inheritance.ToString(), inherited, propagation.ToString(), sid.ToString(), rights.ToString());
        si.Dacl.Add(ace);
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

![execution](https://cloud.githubusercontent.com/assets/5282389/14872487/c4010e46-0cba-11e6-9647-52d205a4746a.png)

![ntfsexplorer](https://cloud.githubusercontent.com/assets/5282389/14872336/4022595a-0cb9-11e6-8fbb-c1810c199ea6.png)

**Comment by Yomodo** [comment]
@AlexLaroche Could you compare with System.IO to see if there's a difference?

**Comment by AlexLaroche** [comment]
I have understand the problem. If you check the "inheranceFlags" on the screencapture, you will that is at "containerInherit". The "ReadAndExecute" permission with "containerInherit" is equivalent of the permission "List folder content". Thanks for your help.
