### ISSUE TITLE
Question mark '?' character in remote UNC Mac path causes ArgumentException in Path.GetLongFrom83ShortPath

### ISSUE THREAD

**Issue by cosinekitty** [alphaleonis/AlphaFS#225]
AlphaFS has been hugely useful to me in getting around the severe problems with path length limits in .NET. Thank you!  I did run into this problem, however. Running my code on Windows, I have a network share that refers to a Macintosh.  Mac-OS apparently allows question mark characters ('?') in its filenames.  Essentially my code is getting an ArgumentException when it does the following:

```
string longpath = Path.GetLongFrom83ShortPath(@"\\MAC-MINI\iTunes\iTunes Music\West, Gould & Fitzgerald\A Walk To Remember\11 So What Does It All Mean?.mp3");
```

Here is the relevant part of the stack trace:

```
System.ArgumentException: Illegal characters: [?] in path.
Parameter name: \\MAC-MINI\iTunes\iTunes Music\West, Gould & Fitzgerald\A Walk To Remember\11 So What Does It All Mean?.mp3
at Alphaleonis.Win32.Filesystem.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
at Alphaleonis.Win32.Filesystem.Path.GetFullPathInternal(KernelTransaction transaction, String path, GetFullPathOptions options)
at Alphaleonis.Win32.Filesystem.Path.GetLongShort83PathInternal(KernelTransaction transaction, String path, Boolean getShort)
```

Is it possible to relax the rules for invalid path characters for UNC paths?  Such paths do not necessarily represent a Windows filesystem, and the question mark character is valid on Mac OS and Linux.

I'm not sure how to work around this, because even if I avoid calling this particular AlphaFS function, I suspect I will encounter similar problems with the other AlphaFS functions I must call passing a filename like this, most critically FileInfo.Exists and File.Open().

Thank you!

**Comment by Yomodo** [comment]
Hi, unfortunately, the '?' character is not allowed on Windows in filenames, paths.
Relaxing the rules is not an option as this would divert from the .NET rules.

So in short, there is no solution for this.

**Comment by cosinekitty** [comment]
OK. For the sake of anyone else who is curious, I did an experiment whose outcome was interesting. On my Debian Linux machine I created a Samba share. Inside the shared directory, I created a file called `qmark?.txt`. When I look at that shared folder from my Windows machine I see:

```
11:32:29 Z:\alphafs>dir
 Volume in drive Z is DonPublic
 Volume Serial Number is 8532-EBA0

 Directory of Z:\alphafs

05/29/2016  11:26 AM    <DIR>          .
05/29/2016  11:25 AM    <DIR>          ..
05/29/2016  11:26 AM                21 Q61HMO~C.TXT
               1 File(s)             21 bytes
               2 Dir(s)  585,195,065,344 bytes free
```

Any attempt to open the file using its original name fails:

```
11:33:27 Z:\alphafs>type "qmark?.txt"
The system cannot find the file specified.
```

I'm in a difficult position because my application obtains the original filename from an iTunes xml configuration file, and there is no way to correlate it with the mangled name like `Q61HMO~C.TXT`. However, that is not AlphaFS's fault!  I suppose for now I will just have to skip filenames that contain characters that are illegal in Windows.

Thanks for responding!

**Comment by Yomodo** [comment]
Perhaps this can be of some help:

1) Use method: **Directory.EnumerateFileSystemEntryInfos()** to enumerate all folders and files.
See docs: http://alphafs.alphaleonis.com/doc/2.0/api/html/14D29A7D.htm

2) Make sure the returned type is of instance type: **FileSystemEntryInfo**
Perhaps one of the properties may contain something useful for you to use, as in correlating info.
(I'm thinking of property: AlternateFileName)
See docs: http://alphafs.alphaleonis.com/doc/2.0/api/html/3B7B5AD0.htm
