### ISSUE TITLE
DirectoryInfo using searchoption

### ISSUE THREAD

**Issue by aartatimago** [alphaleonis/AlphaFS#226]
Hello,
I ran into problems with a too long full path name, and then I discovered this project.
So I'm testing it and it looks like that I have ran into a slight problem.

long lnFileSize = new DirecoryInfo(psDir).GetFiles("*.ps", System.IO.SearchOption.TopDirectoryOnly).Sum(file => file.Length);

In a directory it also counts the files with a extension ".eps", when I use the standard system.io library these files are not counted.

Looking forward to your answer.

**Comment by Yomodo** [comment]
The search filter used is not a comprehensive implementation, which unfortunately can result in false positives.

**Comment by Yomodo** [comment]
From the looks of it, [this ](https://github.com/exocad/exoAlphaFS/issues/1) will be implemented.
