### ISSUE TITLE
file.copy 

### ISSUE THREAD

**Issue by ghost** [alphaleonis/AlphaFS#227]
Attempting to copy a long path from a local drive to a network mapped drive. Getting this:
System.NotSupportedException: The given path's format is not supported
Same thing happens with URL.

Using 2 string variables, the contents of which are:
C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913 Revision # 1 Chuck Haeuser Siteworks Landscape Inc Exterior Steel Guardrail and Handrail 44 Hill Drive Kentfield CA.pdf

and 

Q:\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913 Revision # 1 Chuck Haeuser Siteworks Landscape Inc Exterior Steel Guardrail and Handrail 44 Hill Drive Kentfield CA.pdf

Exact error is:
System.Exception.ToString returned "System.NotSupportedException: The given path's format is not supported: [ C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913 Revision # 1 Chuck Haeuser Siteworks Landscape Inc Exterior Steel Guardrail and Handrail 44 Hill Drive Kentfield CA.pdf]" & vbCrLf & " at Alphaleonis.Win32.Filesystem.Path.CheckValidPath(String path, Boolean checkInvalidPathChars, Boolean checkAdditional) in d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.ValidationAndChecks.cs:line 192" & vbCrLf & " at Alphaleonis.Win32.Filesystem.File.CopyMoveInternal(Boolean isFolder, KernelTransaction transaction, String sourceFileName, String destinationFileName, Boolean preserveDates, Nullable1 copyOptions, Nullable1 moveOptions, CopyMoveProgressRoutine progressHandler, Object userProgressData, PathFormat pathFormat) in d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\File Class\File.CopyMove.cs:line 1076" & vbCrLf & " at Alphaleonis.Win32.Filesystem.File.Copy(String sourceFileName, String destinationFileName, Boolean overwrite) in d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\File Class\File.CopyMove.cs:line 78" & vbCrLf & " at CopyFast.Form1.ProcessFiles()" String

**Comment by OaklandA** [comment]
BTW, this is version 2.0.1.0, in VB.NET 2015.
Doesn't matter if overwrite or not.  
The file doesn't exist in the target.
Don't know what else I can tell you about this, but if there is something I'm not doing right, please let me know.  It's just a Simple file.copy(src, dest)

**Comment by ghost** [comment]
This is a simple file.copy(src, dest).
Doesn't matter if it is overwrite or append.
File does not exist in dest.
vb.net 2015

**Comment by mikequinlan** [comment]
I was curious so I ran a test and "it works for me". What version of AlphaFS are you using? Also, I notice that one of your directory names has an extension that begins with a space character -- "\Mclaughlin. Kentfield\" has a blank after the period which might cause problems.

**Comment by ghost** [comment]
Using version 2.0.1.0
Not in control of what users name files and folders, unfortunately.

**Comment by mikequinlan** [comment]
I've attached my test project. It attempts (successfully on my system) to copy a file with that file name.

I copy it to 4 different destinations to see if the destination file system had any effect -- C: uses the NTFS file system, E: uses ReFS, F: uses Fat32, and Y: is a network drive using the Parallels file system (HFS+). This is running on Windows 10 64-bit version 1607 (the most recent Preview build).

[Test2.zip](https://github.com/alphaleonis/AlphaFS/files/345196/Test2.zip)

**Comment by Yomodo** [comment]
.NET usually has an issue with spaces in paths. To get around this, try the `File.Copy()` overload that supports the [PathFormat](http://alphafs.alphaleonis.com/doc/2.0/api/html/C8D14B27.htm).**LongFullPath** as this will skip path validation.

**Comment by ghost** [comment]
Back at it after being away, but still no joy.
Here is a snippet of the code in question:

```
Public Shared Sub ProcessFiles()

    '  Read from the list of files that exist on the Source, but not on the Target, and copy them one by one to the Target server.
    Dim FileList = New IO.StreamReader("C:\shared\Siteworks\xfer\FrmTgt\filelist.txt")
    Dim InputLine As String
    Dim DestinationFile As String = ""

    Do
        InputLine = FileList.ReadLine()
        DestinationFile = ConvertPath(InputLine)

        Try
            Win32.Filesystem.File.Copy(InputLine, DestinationFile, pathFormat:=Win32.Filesystem.PathFormat.LongFullPath)
        Catch ex As Exception
            MessageBox.Show(ex.ToString)
        End Try

    Loop Until InputLine = Nothing

End Sub
Public Shared Function ConvertPath(Path As String) As String

    '  Correct the path to the destination directory.
    Dim trunc As String = Path

    trunc = trunc.Remove(0, 21)
    trunc = "q:\siteworks\" & trunc

    Return trunc

End Function
```

**Comment by ghost** [comment]
I tried manually putting the path in code, from copying the path and filename from explorer, and it still acts like it can't find the source file.

**Comment by Yomodo** [comment]
I don't think you can change (truncate) the original path and expect it to get it working.

**Comment by ghost** [comment]
If you take another look, you will see I am stripping "C:\shared\Siteworks" off the original path and replacing it with "Q:\siteworks", and assigning that to the destination path.  The original input doesn't change.

**Comment by mikequinlan** [comment]
You say you are stripping "C:\shared\Siteworks" off the original path but
that is not quite true. You are removing the first 21 characters from the
original path (trunc.Remove(0, 21)) but "C:\shared\Siteworks" is only 19
characters long. In other words you are changing

C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files
2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913 Revision # 1
Chuck Haeuser Siteworks Landscape Inc Exterior Steel Guardrail and Handrail
44 Hill Drive Kentfield CA.pdf

to

q:\siteworks\sers Shared Folders\Project Management\Project Files
2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913 Revision # 1
Chuck Haeuser Siteworks Landscape Inc Exterior Steel Guardrail and Handrail
44 Hill Drive Kentfield CA.pdf

**Comment by ghost** [comment]
Not quite so.  There is a leading space in the list I'm taking from.  I corrected that and now use a trim() command to make sure I'm not dealing with leading or trailing spaces, but I get the same result.

Funny thing is if I cd to the path in a CMD prompt and try to copy that file to c:\test, even using wildcard (e.g. copy p*.pdf c:\test) I get "path not found.".  Dir *.pdf does show the file.

**Comment by Yomodo** [comment]
Up until .NET 3.5. it was possible to create files/folders with a space in the name. Starting with .NET 4+ this is not possibly any more. All other characters seem to be valid characters, so that makes it a bit hard what exactly is causing the NotSupportedException.  Does this exception also happen when using System.IO or doesn't it get that far because of... PathTooLong ?

**Comment by ghost** [comment]
ssystem.io gives PathTooLong exception.
Thing is, I have about 1600 files that can't be copied like this.  I've looked for commonality and found none, except for spaces in path and filename, plus they all exceed 260 chars.   All of them were copied to this server by Robocopy.

**Comment by ghost** [comment]
What makes this even more mysterious is that the list of files is generated by code using AlphaFS to get the dateTime and file name on the source server, then the complete list is passed to the target server.  The target server then goes through the files it has on hand.  Any that are found to be out of date, or do not exist are written to this list.  The source server picks up this trimmed down list, and processes the files.  All the ones marked as out of date get copied correctly, but the 1600 or so that are  PathTooLong do not make it.  Interesting to me that AlphaFS can get the DateTime correct on all these files, but can't seem to find them later.  Going through the code that creates the list now.  Is there anything I should watch for, such as ANSI/ASCII?  Anything?

**Comment by ghost** [comment]
I have simplified it down to the following.  Note that if the file.exists() fails, the Try would never execute, but it does, and the file.copy() fails.

If file.exists() can find the file, something is wrong, and it isn't a path or filename problem.

Imports Alphaleonis

Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

```
    If File.Exists("C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913   Revision # 1   Chuck Haeuser   Siteworks Landscape Inc   Exterior Steel Guardrail and Handrail   44 Hill Drive Kentfield CA.pdf") Then
        Try
            File.Copy("C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913   Revision # 1   Chuck Haeuser   Siteworks Landscape Inc   Exterior Steel Guardrail and Handrail   44 Hill Drive Kentfield CA.pdf", "C:\temp\test.pdf", PathFormat.LongFullPath)
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

    End If
End Sub
```

End Class

**Comment by ghost** [comment]
actually the above gives a slightly different error, but I don't understand how file.exists() can find the file, but file.copy() can't.  The literal value is the same for both. Even File.GetLastWriteTime() succeeds in reading the correct datetime.
{"(3) The system cannot find the path specified: [C:\shared\Siteworks\Users Shared Folders\Project Management\Project Files 2008\Project Files 2008\Mclaughlin. Kentfield\Proposal # 1913   Revision # 1   Chuck Haeuser   Siteworks Landscape Inc   Exterior Steel Guardrail and Handrail   44 Hill Drive Kentfield CA.pdf]"}

**Comment by ghost** [comment]
You don't seem to care, but I thought I should share this for anybody looking for the answer.  This solved the problem for me:
https://support.microsoft.com/en-us/kb/2891362
Thanks.

**Comment by Yomodo** [comment]
Thank you for the solution!

On a side note: I've spent massive amounts of hours on AlphaFS, based on free will and enthusiasm.
I'm sorry you feel this way.
