### ISSUE TITLE
Question: Why does Alphaleonis.Win32.Filesystem.File.GetSize throws Win32.NativeError File being used by another process

### ISSUE THREAD

**Issue by albvar** [alphaleonis/AlphaFS#228]
Using version 2.1.0.0 - thanks in advance for your help.

 Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
Message:
"(32) The process cannot access the file because it is being used by another process: [\\?\UNC\myServer\myShare\myFolder\myFile.myExtention]"

This file is indeed being used by another program. I did a little bit of reading on this (correct me if wrong).
There are two ways to determine a files size
1) Looking at the files metadata - does not lock the file but not as accurate
2) Placing a lock on the file and retrieving the files size. (Used by GetSize method).

Is there a way to use GetSize without locking the file? I believe I can also accomplish this by
using AlphaFS's DirectoryInfo(string path).Length property which DOES not lock the file.

How to reproduce issue:
1. Lock a file on your file system
# Here is an example using powershell

$file = [System.IO.File]::Open('C:\temp\test.txt', 'Open', 'Read', 'None')
// Back to C#
var fileSize = Alphaleonis.Win32.Filesystem.File.GetSize(@"C:\temp\test.txt")
// This should throw the error
# Powershell - Close the file

$file.Close()

**Comment by Yomodo** [comment]
The `System.IO.IOException` is thrown because somewhere down the road the Win32 API `CreateFile()` is called to open the file.

The file however gets locked because of the share mode: `None`.
If you change the last parameter from `None` to `Read`, `File.GetSize()` will be able to read the file size without throwing an `System.IO.IOException`.
