### ISSUE TITLE
CheckInvalidPathChars breaks IsPathRooted for whitespace strings

### ISSUE THREAD

**Issue by krismaz** [alphaleonis/AlphaFS#234]
CheckInvalidPathChars throws an error when provided with the empty string, or strings containing only whitespace.

IsPathRooted uses this to check for invalid characters, and thus breaks when the input is one of these strings, when the correct behaviour would be to return false. Note that certain special characters should still be disallowed to match System.IO behaviour for e.g. "\t \n".

I first noticed the bug when using IsPathRooted, but I suspect it might be present in other methods where the input string might not necessarily be a true path.

**Comment by Yomodo** [comment]
@krismaz Could you please verify it is ok now?
Should be fixed with commit: 72688273083d5a6a453fda147b79332601a0f296

**Comment by krismaz** [comment]
7268827 appears to have resolved the issue :+1:
