### ISSUE TITLE
Issue #216 has been closed prematurely. The problem still exists in latest code. 

### ISSUE THREAD

**Issue by warrenlbrown** [alphaleonis/AlphaFS#236]
Issue #216 has been closed prematurely. The problem still exists in latest code. The tests did not reflect the actual problem. Ergo, let me clarify a bit more:

`Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\temp\");  returns TRUE`
`Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\");  returns FALSE`

Thank you very much.

**Comment by Yomodo** [comment]
Shouldn't the paths be: @"\\?\c:\temp\" and @"\\?\c:\"
Note the start with two backslashes.

**Comment by warrenlbrown** [comment]
Yes, looks like something removed the extra, even as it did your email to me (see below).  Thanks.

@"\\?\c:\temp\" and @"\\?\c:\"

**Comment by warrenlbrown** [comment]
Actually, the problem is that the raw text is correct as I posted (you can see correct value if you go into edit mode), but needed to be put into ‘insert code’ annotation for display/view purposes.

From: Warren Brown
Sent: Wednesday, August 24, 2016 10:00 AM
To: 'alphaleonis/AlphaFS' <reply@reply.github.com>; alphaleonis/AlphaFS <AlphaFS@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [alphaleonis/AlphaFS] Issue #216 has been closed prematurely. The problem still exists in latest code. (#236)

Yes, looks like something removed the extra, even as it did your email to me (see below).  Thanks.

@"\\?\c:\temp\<file://%3f/c:/temp/>" and @"\\?\c:\<file://%3f/c:/>"

**Comment by Yomodo** [comment]
These are the current AlphaFS (2.1.0.0) results:

```
Path: c:\            System.IO: True    AlphaFS  : True
Path: \\?\c:\        System.IO: False   AlphaFS  : False
Path: \\?\c:\temp\   System.IO: False   AlphaFS  : True    <-- AlphaFS discrepancy.
Path: c:\temp\       System.IO: True    AlphaFS  : True
```

Upon investigation System.IO internally throws a `System.ArgumentException: Illegal characters in path` when encountering the long path notation: \\?\, returning `False` as a result, even if the folder exists.

AlphaFS will only return `False` if the folder does not exists.

Although AlphaFS should mirror System.IO as closely as possible, this is a situation that will probably not be fixed.
