### ISSUE TITLE
How to use AlphaFS to make list of long path files with creationdate

### ISSUE THREAD

**Issue by noppGithub** [alphaleonis/AlphaFS#237]
I heard that AlphaFS can list the file with over 260 characters path length,
I i'm now learning to this AlphaFS, but not sure if I can use it correctly.

Can someone guide me how to get the list of FullName with CreationDate on long path files using AlphaFS ?

I'm also get this error during install(even Unblock is checked).

```
PS D:\dropbox>
PS D:\dropbox>
PS D:\dropbox> import-module -name 'D:\Download\AlphaFS.2.0.1\AlphaFS.2.0.1\lib\net45\AlphaFS.dll'
import-module : Could not load file or assembly 'file:///D:\Download\AlphaFS.2.0.1\AlphaFS.2.0.1\lib\net45\AlphaFS.dll' or
one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ import-module -name 'D:\Download\AlphaFS.2.0.1\AlphaFS.2.0.1\lib\net4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Thanks alot.

**Comment by MickyBalladelli** [comment]
if you right-click the AlphaFS.dll file, does it say it's blocked? You can use PowerShell to unblock it via Unblock-File

**Comment by Yomodo** [comment]
What version of .NET is installed/are you using?
Check it using this:

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10240.16384
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000      <-- .NET version currently in use.
BuildVersion                   10.0.10240.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by Yomodo** [comment]
[DirectoryInfo.EnumerateFiles](https://msdn.microsoft.com/en-us/library/dd413232%28v=vs.110%29.aspx)

[File.GetCreationTime](https://msdn.microsoft.com/en-us/library/system.io.file.getcreationtime%28v=vs.110%29.aspx)

Replace `System.IO.File` (.NET) with `Alphaleonis.Win32.Filesystem.File`
Also take a look at the unit tests to see how things are done.

**Comment by noppGithub** [comment]
@Yomodo THank you so much, now i can use AlphaFS to list file over 260 characters. Is there any method to get permission of each files (recursive) under specified directory using AlphaFS ?

**Comment by Yomodo** [comment]
With [File.GetAccessControl](https://msdn.microsoft.com/en-us/library/8e1fc3b8%28v=vs.110%29.aspx) you can get the security information.
You can use a `for/each` loop using [Directory.EnumerateFiles](https://msdn.microsoft.com/en-us/library/dd383571%28v=vs.110%29.aspx) with `SearchOption.AllDirectories` to go recursive.
