### ISSUE TITLE
Retrieving owner and LastWriteTime of files with specific extension

### ISSUE THREAD

**Issue by M4ssiveDynamic** [alphaleonis/AlphaFS#238]
I'm trying to retrieve all files from all my harddrives with the exe and html extension, plus the file owner and LastWriteTime. I first tried to retrieve all HDD ID's, store them in an array, loop through it with foreach and insert the variable instead of the Get-Location command, but I always got an error (illegal character \* used). That's why I'm executing the code below for every hard drive in my array. 

This is my code so far: 

`if ($drives -contains "E:") 
{
    cd E:\Data     # I did this so Get-Location works, because I couldn't get the syntax of GetFiles right
    ([Alphaleonis.Win32.Filesystem.Directory]::GetFiles((Get-Location).Path, '*.exe', [System.IO.SearchOption]::AllDirectories)) | Out-File $rep -Append
    ([Alphaleonis.Win32.Filesystem.Directory]::GetFiles((Get-Location).Path, '*.html', [System.IO.SearchOption]::AllDirectories)) | Out-File $rep -Append  
}` 

This code only retrieves the files with the wanted extensions and outputs them in a CSV file. 
- **But how do I get the owner and LastWriteTime of this files?** 
- **And  what is the proper way for inserting the path in GetFiles?** 
  I tried something like this: `'E:\Data'` or `"E:\Data"` also without quotes and trailing slash etc., but it always gave me an error because of the \* character. With Get-Location it works fine. 

I believe there's a way to merge this two commands AlphaFS above in one, but I'm new to AlphaFS and scripting, so I haven't found a solution yet. 

Thanks alot!

**Comment by Yomodo** [comment]
This works on my system:
`[Alphaleonis.Win32.Filesystem.Directory]::GetFiles("$((Get-Location).Path)", '*.exe')`
`[Alphaleonis.Win32.Filesystem.Directory]::GetFiles('C:\Users\ikke\Downloads', '*.exe')`

Check the [FileSystemInfo.LastWriteTime](https://msdn.microsoft.com/en-us/library/system.io.filesysteminfo.lastwritetime%28v=vs.110%29.aspx) properties and [File.GetAccessControl](https://msdn.microsoft.com/en-us/library/8e1fc3b8%28v=vs.110%29.aspx) methods.
