### ISSUE TITLE
Issue #236 has been closed prematurely. The problem still exists in latest code. 

### ISSUE THREAD

**Issue by warrenlbrown** [alphaleonis/AlphaFS#243]
Thank you for your quick responses, but I believe there is still a problem. I will try to re-re-clarify the situation again (sorry, but I'm having trouble with the double backslash display in preview mode, so please edit the comment to see the original syntax): 

`// c:\temp handling is ok. Both libs return TRUE
System.IO.Directory.Exists(@"c:\temp\"); returns TRUE
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\temp\"); returns TRUE

// c:\ handling is not ok. System.IO returns TRUE, but Alphaleonis returns FALSE
System.IO.Directory.Exists(@"c:\"); returns TRUE
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\"); returns FALSE`

**Comment by Yomodo** [comment]
(4 backslashes will create 2 backslashes)
Have you tested this with the latest development build?

**Comment by warrenlbrown** [comment]
I did with the latest build when I submitted #236. But I’ll test again with the latest latest. Thanks.

**Comment by Yomodo** [comment]
With the latest dev build, this is what I get:

// False
`Console.WriteLine(System.IO.Directory.Exists(@"\\?\c:\"));`

// False
`Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\"));`

// True
`Console.WriteLine(System.IO.Directory.Exists(@"c:\"));`

// True
`Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"c:\"));`

**Comment by warrenlbrown** [comment]
The latest, latest, latest code now seems to fix the problem. Many thanks.

**Comment by Yomodo** [comment]
I'm currently cleaning up the unit tests, which one is this that you're mentioning?

**Comment by warrenlbrown** [comment]
AlphaFS.UnitTest\Directory Class\CreateDirectory.cs, method Directory_CreateDirectory


Or just search for “// MSDN: .NET 4+ Trailing spaces”
