### ISSUE TITLE
Rename and update documentation for Add/RemoveDirectorySeparator methods.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#25]
AddDirectorySeparator should be renamed to AddTrailingDirectorySeparator to clarify its purpose. Its documentation should be updated to reflect that this is what it is doing. Also documentation needs to be updated to reflect what the difference between this method and GetSuffixedDirectoryName is.

RemoveDirectorySeparator should consequently be renamed to RemoveTrailingDirectorySeparator. Same updates to documentation.

**Comment by Yomodo** [comment]
I did not merge and had already deleted the branch.

START AGAIN.
