### ISSUE TITLE
Creating Folder with Empty name

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#255]
Hi,

i tried to create the next folder path, "c:\temp\\folder1\ \folder2///   folder3" and got the next
result c:\temp\folder1 were created, inside a folder with empty name (just the folder icon with no name) was created, inside again a folder with empty name (just the folder icon with no name) was created, and then inside the folder2 was created, when clicking on it a message box appear with the next message:

"C:\temp\folder1\ \ \folder2 folders refers to a location that is unavailable. It could be on a hard drive on this computer.or on a network. Check to make sure that the disk is properly inserted, or that you are connected to the Internet or your network and then try again. If it still cannot be located the information might have been moved to a different location."

when trying this with the System.IO it creates the next path c:\temp\folder1\folder2\folder3.

**Comment by Yomodo** [comment]
Hi! It seems your paths has spaces in it: C:\temp\folder1\ \ \folder2

AlphaFS allows the creation of folders and files with a space in the name,
although this only happens if the PathFormat is specified. 

So what syntax did you use?

**Comment by ardestan** [comment]
Hi,

The path contains spaces, but it seems that if the space sorround with "\" it treated as empty folder name. i'm using the CreateDirectory(string path) method, without the PathFormat.

**Comment by Yomodo** [comment]
I'm assuming you're using version 2.0.1?
Could you also test with the latest development build? (2.1.0.0)

**Comment by ardestan** [comment]
Where can i found this version?

**Comment by Yomodo** [comment]
Please find it here: https://github.com/alphaleonis/AlphaFS
I've uploaded two compiled AlphaFS.dll zip files for .NET 3.5 and .NET 4.0

**Comment by ardestan** [comment]
Hi,

i tried the new dll, and experienced the same behavior as i described above.

**Comment by ardestan** [comment]
The new dll has another issue, when i use the CreateDirectory(string path, PathType pathType)
passing the "c:\temp\folder1\ \folder2/// folder3" and set the pathType to FullPath or LongFullPath
i'm getting exception, only RelativePath is working.

**Comment by Yomodo** [comment]
How do you get paths like these in the first place?

**Comment by ardestan** [comment]
we want to use this dll in our projects, we run some tests to make sure it behaves as System.IO, so
we shouldn't have any unexpected behavior, and that we safe from user/programmer errors, such scenario
might happen when you write code.
Maybe you can add this test to the unit tests project.

**Comment by Yomodo** [comment]
Ok, but notice that chances are that this may not be fixed 100%.
