### ISSUE TITLE
Provide downloadable documentation in .chm format.

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#258]
Hi,

can you attach the documentation to the project as .chm or .pdf file?

**Comment by alphaleonis** [comment]
I've added the .chm format as an output to the documentation project. This will be available for download starting in the 2.1 release.

**Comment by ardestan** [comment]
Thanks.

**Comment by ardestan** [comment]
Can you please, provide also a list of the supported operating systems you tested the dll on.

**Comment by Yomodo** [comment]
@alphaleonis 

Subject: RE: AlphaFS: Regarding Documentation Problems
Date: Sat, 3 Jan 2015 13:05:50 +0100
**Exactly. Good, but then we’ll skip the CHM.**

Yomodo:
I agree, online help is so much easier.
Also can't really think of any advantage by maintainingan extra CHM file, it only means more work for us.

**Comment by alphaleonis** [comment]
@yomodo: This is why I prefer verbal communication. The written word is too easily used against you. ;) 
But anyway, I did not believe anyone would want the chm-file. Apparently some people do. And frankly, there is really no extra work at all to provide it currently. (the new build script places it in the zip it creates, so I don't see the problem of including it in the build. 

Or am I missing something?

**Comment by Yomodo** [comment]
Haha.. anything you write can and will...
Reading back the mails, the main reason for dropping the chm was questions from users why
they could not open the file, because of version differences. And at that time we thought the online help was sufficient.

**Comment by alphaleonis** [comment]
Ah, yes, the eternal problem with opening chm-files that have been downloaded. Yes, forgot about that one. Oh well, either way, we'll just include the CHM for anyone who wants it I think anyway.

**Comment by alphaleonis** [comment]
Fixed in 2.1.
