### ISSUE TITLE
Multiple issues with the Crc32 and Crc64 classes.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#259]
1. They are not CLS-compliant, thus generating many warnings.
2. They do not conform to the coding guidelines, using an `m_`-prefix on private members.
3. They are missing documentation.

These classes seem to be there only to support `File.GetHash`? In that case shouldn't they be made internal rather than public?

**Comment by alphaleonis** [comment]
Also, why did we stop submitting pull-requests for code-review, especially for new features, before checking them in?

**Comment by alphaleonis** [comment]
Ah, just noticed that it was external code that was lifted in with permission from the author. I assume we also have permission to modify the code?

**Comment by Yomodo** [comment]
The written permission from the author, Damien Guard:

> I give my permission to include my crc32.cs and crc64.cs files in your project and you may re-license them under the MIT license to fit with your project. Please also feel free to rename the namespaces to match with what you want to do and change the code/comments etc. as applicable. 
> 
> I would ask that you include my name in the new copyright notice at the top of these two files.

**Comment by alphaleonis** [comment]
Okay, great! :) Thanks.
