### ISSUE TITLE
Remove the two ZIP files from source control.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#262]
These files should not be in the repo, and should be removed.

**Comment by Yomodo** [comment]
Could you please check. I think I interfered somehow, since the .zip files are back?

**Comment by alphaleonis** [comment]
@Yomodo Hehe, you really want those there don't you?  ;)  Alright, I did a rewrite of the history to get rid of them permanently.  Of course, I forgot to tell you that you should get a fresh clone before pushing again, since otherwise this might happen.   So let me know of a time when you don't have anything being worked on and I will fix that.

**Comment by Yomodo** [comment]
:) I'll hold my horses, please go ahead.

**Comment by alphaleonis** [comment]
Alright, cool, just delete your local repo, and do a fresh clone afterwards then. I'll let you know when I'm done.

**Comment by alphaleonis** [comment]
@Yomodo : There, you should be good to go with a fresh clone now! :)
