### ISSUE TITLE
Support for xml and image

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#264]
Hi,

It will make your dll a best solution exists if you support xml (xml serialize/read/write etc..) and image
(Image.FromFile etc...) for long path files.

Thanks.

**Comment by Yomodo** [comment]
How about this, for XML:

var stream = Alphaleonis.Win32.Filesystem.File.Open("product.xml", FileMode.Open, FileAccess.Read))

xmldoc.Load(stream);

**Comment by ardestan** [comment]
This could be a solution, but if we want to follow the main reason someone will want to use the dll, is how easy he can switch from using System.IO to AlphaFS, all methods have same signature, just refference the dll and you ready to go, no code changes are needed, he probably want to have the same approach with xml and images, and again without any code changes from his side.

**Comment by alphaleonis** [comment]
@ardestan What methods in particular are you referring to? Maybe I'm misunderstanding you here? All Xml-classes including serialization works with streams already. And you mention `Image.FromFile`, which happens to be in System.Drawing and really has very little to do with System.IO.  First of all, how would we do anything about that method? We can't reimplement the entire `Image` class, and there is no way to override a static method as the case is here.  And second, there is a huge amount of methods in different classes all around the .NET framework that accept a filename as input. We would essentially have to rewrite the entire .NET framework to replace all of these, and that is just not feasible.

Instead, if you want the type of behavior where you can just swap the libraries out, you need to stay away from methods outside of AlphaFS that accept a filename as input. Pretty much all of these classes accept a `Stream` as an argument, and you would have to use those instead.

**Comment by ardestan** [comment]
I agree with your words, i just tried to give an improvement suggestion, you right, the support for the long path problem will be allways a partial one, because as you mentioned: "there is a huge amount of methods in different classes all around the .NET framework that accept a filename as input", so for now you need to use the stream approach.
