### ISSUE TITLE
There are multiple warnings when building the documentation.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#268]
These should be reviewed and fixed.

**Comment by Yomodo** [comment]
#320

**Comment by alphaleonis** [comment]
I think most of these (if not all) were fixed in the preparation for 2.1.3 in master branch. Still needs merge to develop though. Will you fix this merge @Yomodo?

**Comment by Yomodo** [comment]
Yes, will do.
