### ISSUE TITLE
Directory.DeleteDirectory(): Method can get stuck in an infinite loop.

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#276]
Hi, 
I have test that deletes nested folders on network drive, in Win7 and Server 2012 it works, but on XP it stuck, seems the method is not returning, probably an infinite loop. 
I'm using the next method:
DeleteDirectory(string path, bool recursive), and I set the recursive argument to true.

**Comment by Yomodo** [comment]
I did notice that our current code for deleting directories contains recursion, but I'm not sure it that is the cause. Could you try again with a small(er) folder structure, just to verify that is does work on XP.

**Comment by ardestan** [comment]
Ok, i'll try it.

**Comment by Yomodo** [comment]
I may have found the culprit in code, if `requireEmpty` = `false`:

```
startRemoveDirectory:

case Win32Errors.ERROR_DIR_NOT_EMPTY:
    if (requireEmpty)
        throw new DirectoryNotEmptyException(pathLp);
    goto startRemoveDirectory;
```

Although I would expect the same behaviour on Windows 7 and Server 2012.
Nevertheless, a bug.

**Comment by ardestan** [comment]
Is there different behavior between network and local directories?
According to the culprit, should expect the same behavior for local and network directories as well.

About Win7 and sever 2012:
In my tests, after deleting the nested directories, I'm cheking if deleted using Directory.Exists() method, so in Win7 and server 2012, The tests hit this code line.
So, apparently the method returned and those directories were deleted.

**Comment by Yomodo** [comment]
The behavior  should be the same for local and network drives.
The only thing behaving differently would be the Win32 API, but there's no mention of that in the docs.

**Comment by Yomodo** [comment]
@ardestan I'm positive the issue is solved now. Could you perhaps test it?

**Comment by ardestan** [comment]
Hi, 
Sorry for the late rspond, i was in vacation
in the last 10 days.
where could i found the new dll?

**Comment by ardestan** [comment]
Hi,
Did you released new dll (2.1.1) with your fixes?
I could not found such release.

**Comment by Yomodo** [comment]
No, you'll have to compile this one your self. It has not been released yet.

**Comment by ardestan** [comment]
Hi,

I'm using the last dev branch (version 2.1.1), now on XP it fails to delete nested folders on network path with the next message:
"Folder is not empty"
but on Win7 it works.
