### ISSUE TITLE
Add [MethodImpl(256)] to methods and constructors.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#283]
Inlining a method/property means that the compiler takes it and replaces the calls to it with its contents 
This is done for performance normally.

Should we do this?

**Comment by alphaleonis** [comment]
To what methods in particular? Definitely not to all methods. It is something that should likely be use extremely rarely if I've understood correctly.

**Comment by alphaleonis** [comment]
In addition, I see no reason to apply aggressive inlining to any method performing i/o, since the overhead of the actual call to the method would be negligible to the time spent inside the method. And most methods we have perform i/o I think.

**Comment by Yomodo** [comment]
I think the `Path` class could benefit, that one has less I/O and more string parsing.

**Comment by alphaleonis** [comment]
Remember the phrase "Premature optimization is the root of all evil" ;) ... Also know that not having the attribute does not prevent the JIT from inlining methods, and adding the attribute does not force inlining. It is just a "stronger recommendation" of some sort if I'm not mistaken, and I don't think it should be used without having a good reason to believe it will improve performance.   So if we can make some benchmarks showing that it will improve performance without having any negative effects, then I'm all for it. But without any benchmarking I think it would be the wrong decision.

**Comment by Yomodo** [comment]
I did some basic benchmarking on a couple of methods from the `Path`, `Directory` and `File` classes
only to get the impression that adding the attribute does not add anything in terms of speed/performance.
I am going to close this one.
