### ISSUE TITLE
Can't set DirectoryInfo().Attributes because setter is protected (Develop version)

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#284]
Hi,

My current code i have the next method:

void SetDirectoryAttributes(string dirPath, FileAttributes newAttributes)
{
       DirectoryInfo dirInfo=new DirectoryInfo(dirPath);
       dirInfo.Attributes|=newAttributes;
}

I downloaded the last development branch and build it, when using this new dll, I got error message 
saying that I can't set FileAttributes in DirectoryInfo, because it had only getter and no setter, looking into the code I saw that you made this field setter protected, but the method summary comment says you can apply set and get.

/// <summary>

 
///   Gets or sets the attributes for the current file or directory. 
/// </summary>

 

https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS/Filesystem/FileSystemInfo.cs

**Comment by Yomodo** [comment]
Good catch!
