### ISSUE TITLE
Deleting nested folders on network drive fail on XP (As continue to Bug #276 fix)

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#285]
Hi,

As continue to Bug #276 fix

I'm using the last dev branch (version 2.1.1), now on XP it fails to delete nested folders on network path with the next message:
"Directory is not empty"
but on Win7 it works.

**Comment by Yomodo** [comment]
Yes, the latest fix at least throws an exception instead of getting into an endless loop.

That said...  Makes one wonder why it works on Win 7 and not on XP.

**Comment by ardestan** [comment]
So, how it going to be supported on XP? 
It's basic and important functionality.

It looks like race condition somewhere, do you have an XP machine that you can debug to
find the root cause?

**Comment by Yomodo** [comment]
That's a good question.

I could say: Support for Windows XP has been dropped by Microsoft, so why should AlphaFS maintain it.
But, of course, that's a lame answer and doesn't help anyone.

Unfortunately, I don't have Windows XP on which I can install Visual Studio to troubleshoot.

**Comment by Yomodo** [comment]
Also, when your receive this exception, is the directory indeed NOT empty?
E.g. no hidden files? And this happens only on a network share?

**Comment by ardestan** [comment]
The directory not empty, it has some 
nested subdirectories in it, some
of the subfolders contains some files.
And indeed it happens only on network drive.

About XP support, it's very important to us to have that functionality.

**Comment by Yomodo** [comment]
Could you try something like this, to see if it eventually would delete everything?

    var done = false;
    while (!done)
    {
        try
        {
            Alphaleonis.Win32.Filesystem.Directory.Delete(folder, true);
        }
        catch (DirectoryNotEmptyException)
        {
        }
        done = true;
    }

**Comment by ardestan** [comment]
It probably would not work, because I'm getting an exception when trying to delete
the folders, so, the while will be exited after the first try.

**Comment by Yomodo** [comment]
Could you try something like this, to see if it eventually would delete everything?
The `DirectoryNotEmptyException` will be caught, allowing the loop to continue.

```
var done = false;
while (!done)
{
    try {
        Alphaleonis.Win32.Filesystem.Directory.Delete(folder, true);
        done = true;
    }
    catch (DirectoryNotEmptyException) {}
}
```

**Comment by ardestan** [comment]
But you set the 'done' flag to true after the
catch section, so the while will stopped.

**Comment by Yomodo** [comment]
Please refresh, I corrected the code.

**Comment by ardestan** [comment]
Ignore my last comment, i didn't noticed you changed the code.
I'll try it tomorrow

**Comment by ardestan** [comment]
But I'm affraid we will enter infinite loop
again.

**Comment by Yomodo** [comment]
As long as you did not try the code, we will not know what happens :)

**Comment by ardestan** [comment]
I'll try it.

**Comment by ardestan** [comment]
It's not working in consistent way, sometimes it stuck.

**Comment by Yomodo** [comment]
You mean stuck as in endless looping (again) ?
Are there any other exceptions that are thrown?

**Comment by ardestan** [comment]
I used the code sample from your comment, I didn't log the exceptions.

**Comment by Yomodo** [comment]
Does it work OK when you use .NET for removing the directory? (Assuming no long paths).
Perhaps you are able to install VS on that Windows XP machine and use the step-through debugger?
And, could you post the full stack trace of the Exception?

**Comment by ardestan** [comment]
I can't promise, I'll try to.

**Comment by Yomodo** [comment]
http://zacharykniebel.com/blog/web-development/2013/june/21/solving-the-csharp-bug-when-recursively-deleting-directories

**Comment by ardestan** [comment]
OK, but as I saw you have your own implementation using pinvoke, so I didn't understand the relevancy to C#.
