### ISSUE TITLE
XP rename file fails with error code (123) on network drive

### ISSUE THREAD

**Issue by ardestan** [alphaleonis/AlphaFS#287]
Hi,

My directories structure:
\\ardestan.local\1111111111111111111...\2222222....\150.........\RenamedFile.txt

I nested 150 directories, each directory name length is 30 chars, I succeed to create new text file on last
nested directroy (directory 150), but when trying to rename this file I got the next error message:

"(123) The filename, directory name, or volume label syntax is incorrect: [\\?\UNC\\\ardestan.local\1111111111111111111...\2222222....\150.........\RenamedFile.txt]"

my tests shows that it happens in not deterministic way.

**Comment by Yomodo** [comment]
Internally we discussed the support for Windows XP and we've decided to drop support for this platform.
This issue will not be fixed.

**Comment by ardestan** [comment]
It is a pity, XP should be your concern, because as Microsoft announced in .NET framework 4.6.2 they support the long path issue.
most of the operating systems are supported by this framework, beside XP.

https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/

**Comment by Yomodo** [comment]
AlphaFS calls the same Win32 API's on all Windows platforms. So if there's an error in the Win32 API,
then we cannot solve that as the source of these API's is not available.

**Comment by ardestan** [comment]
But you have your own logic in your project, otherwise, it was only 
p/invoke file for the API methods, nothing to much sophisticated.

**Comment by Yomodo** [comment]
To track this down I would need to have an XP machine (perhaps a virtual machine would do)
and VS that runs on XP. The latter I don't have.

On all platforms greater than Windows XP it works well, so we can assume the logic is OK.
For unknown reasons it fails on XP and I just don't have the means to track this.

Of course, **you** can also try to track down this bug and come up with a possible solution, which I will be happy to integrate.
