### ISSUE TITLE
Directory.Exists on root drive problem has come back with recent updates

### ISSUE THREAD

**Issue by warrenlbrown** [alphaleonis/AlphaFS#288]
In 2.1.2 release:
`
> var x = Directory.Exists(@"\\\\?\c:\\");
> x
false
> x = Directory.Exists(@"\\\\?\c:\\temp\\");
> x
true
`

**Comment by Yomodo** [comment]
You are talking about the v2.1.2 release?

**Comment by warrenlbrown** [comment]
yes

**Comment by Yomodo** [comment]
Strange, this is what I get:

```
  // False
  Console.WriteLine(System.IO.Directory.Exists(@"\\?\c:\"));
  Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\"));

  // True
  Console.WriteLine(System.IO.Directory.Exists(@"c:\"));
  Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"c:\"));


  // False
  Console.WriteLine(System.IO.Directory.Exists(@"\\?\c:\temp2\"));
  Console.WriteLine(Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\temp2\"));
```

**Comment by warrenlbrown** [comment]
I don't believe you're testing to see the differences that I think I'm seeing.

You cannot compare anything with System.IO as far as the long path prefix is concerned, so, let's try a different approach to clarify:

Assuming that c:\temp exists on your machine:
The following returns true:
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\temp\");
Ergo the following should return true, but it does not:
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\");

**Comment by Yomodo** [comment]
As I stated in #216, AlphaFS should mirror System.IO as closely as possible.

There's at least one exception: Checking the existence on the root drive is a bit
different than checking it on a sub folder:

```
Path: \\?\c:\temp\   System.IO: False   AlphaFS  : True    <-- AlphaFS discrepancy.
```

You also don't need to apply the long path prefix, AlphaFS will take care of this internally.

**Comment by warrenlbrown** [comment]
I still feel like we are talking at cross purposes.

Following is correct and desired, which is good:
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\temp\");

Since this temp directory exists, then the drive directory root should also exist when I do the following, but it does not:
Alphaleonis.Win32.Filesystem.Directory.Exists(@"\\?\c:\");

If I use System.IO, then following is good:
System.IO.Directory.Exists(@"c:\temp\");

and also following is good
System.IO.Directory.Exists(@"c:\");

**Comment by Yomodo** [comment]
The `temp` folder and the `root drive` are two different things, so they can't/ shouldn't
be compared equally (in the same way).

Better yet, if you need to check for the drive, you should use the `DriveInfo` class for that.

**Comment by warrenlbrown** [comment]
Thank you again for your responses.

The scenario is that a particular application allows a user to specify any given path/directory (including the root directory) on the system as the target for the creation of some file. It is then useful to confirm that that directory exists before trying to do anything else with the directory.

So a user might specify c:\temp
Or c:\
or d:\some\other\directory

It would seem that we should be able to call the alphafs Directory.Exists on any of those variants without doing special parsing.

The reason we do the prefixing is because older versions of AlphaFS seemed to require it. And we have not taken the time to remove the prefixing for newer builds of AlphaFS.

**Comment by Yomodo** [comment]
Could you try with the development build?
I'm suspecting this fix did not make it into the current prod (v2.1.2) release.

**Comment by warrenlbrown** [comment]
I was testing with latest. So I pulled latest again. And still same problem

**Comment by warrenlbrown** [comment]
Thank you, but this is only partially fixed. Shall I open a new issue, or add problem details to this one?

**Comment by warrenlbrown** [comment]
A change in code that would go a long way toward fixing most of the remaining problems is in the ExistsCore method. Change:

`              var pathLp = Path.GetExtendedLengthPathCore(transaction, path, pathFormat, GetFullPathOptions.TrimEnd  | GetFullPathOptions.RemoveTrailingDirectorySeparator | GetFullPathOptions.CheckInvalidPathChars | GetFullPathOptions.ContinueOnNonExist);`

to:
`            var pathLp = Path.GetExtendedLengthPathCore(transaction, path, pathFormat, GetFullPathOptions.TrimEnd | GetFullPathOptions.CheckInvalidPathChars | GetFullPathOptions.ContinueOnNonExist);`

This will allow the following dirspec to work properly:
`\\?\c:\`

But still does not deal with the remaining problem:
`\\?\c:temp`

Interesting the following does work:
`\\?\c:temp\`

Some suggestions for unit testing coverage:
`Directory \\?\c:\ exists`
`Directory \\?\c: exists`
`Directory \\?\c:\temp exists`
`Directory \\?\c:\temp\ exists`
`Directory \\?\c:\nonexistent does not exists`
`Directory \\?\c:\nonexistent\ does not exists`
`Directory c:\nonexistent does not exists`
`Directory c:\nonexistent\ does not exists`
`Directory c:\temp exists`
`Directory c:\temp\ exists`
`Directory c: exists`
`Directory c:\ exists`
`Directory c:temp does not exists`
`Directory \\?\c:temp does not exists`
`Directory \\?\c:temp\ does not exists`
`Directory c:\temp\ exists`

**Comment by Yomodo** [comment]
To verify, did these remaining problems used to work well, before v2.1.2?

**Comment by warrenlbrown** [comment]
I don't think so.

**Comment by Yomodo** [comment]
Windows 10 1703 (Build 15063.909):

    System.IO   (should be FALSE):	[False]		directory= C:\jrrb3üjn.w15
    AlphaFS     (should be FALSE):	[False]		directory= C:\jrrb3üjn.w15

    System.IO   (should be FALSE):	[False]		directory= C:jrrb3üjn.w15
    AlphaFS     (should be FALSE):	[False]		directory= C:jrrb3üjn.w15

    System.IO   (should be FALSE):	[False]		directory= C:\jrrb3üjn.w15\
    AlphaFS     (should be FALSE):	[False]		directory= C:\jrrb3üjn.w15\

    System.IO   (should be FALSE):	[False]		directory= C:jrrb3üjn.w15\
    AlphaFS     (should be FALSE):	[False]		directory= C:jrrb3üjn.w15\

    System.IO   (should be TRUE):	[True]		directory= C:\jrrb3üjn.w15-exists
    AlphaFS     (should be TRUE):	[True]		directory= C:\jrrb3üjn.w15-exists

    System.IO   (should be FALSE):	[False]		directory= C:jrrb3üjn.w15-exists
    AlphaFS     (should be FALSE):	[False]		directory= C:jrrb3üjn.w15-exists

    System.IO   (should be TRUE):	[True]		directory= C:\jrrb3üjn.w15-exists\
    AlphaFS     (should be TRUE):	[True]		directory= C:\jrrb3üjn.w15-exists\

    System.IO   (should be FALSE):	[False]		directory= C:jrrb3üjn.w15-exists\
    AlphaFS     (should be FALSE):	[False]		directory= C:jrrb3üjn.w15-exists\


Server 2012R2

    System.IO   (should be FALSE):	[False]		directory= C:\1mrty450.fnd
    AlphaFS     (should be FALSE):	[False]		directory= C:\1mrty450.fnd

    System.IO   (should be FALSE):	[False]		directory= C:1mrty450.fnd
    AlphaFS     (should be FALSE):	[False]		directory= C:1mrty450.fnd

    System.IO   (should be FALSE):	[False]		directory= C:\1mrty450.fnd\
    AlphaFS     (should be FALSE):	[False]		directory= C:\1mrty450.fnd\

    System.IO   (should be FALSE):	[False]		directory= C:1mrty450.fnd\
    AlphaFS     (should be FALSE):	[False]		directory= C:1mrty450.fnd\

    System.IO   (should be TRUE):	[True]		directory= C:\1mrty450.fnd-exists
    AlphaFS     (should be TRUE):	[True]		directory= C:\1mrty450.fnd-exists

    System.IO   (should be FALSE):	[True]		directory= C:1mrty450.fnd-exists
    AlphaFS     (should be FALSE):	[False]		directory= C:1mrty450.fnd-exists
    
    Aborted because of mismatch.

**Comment by Yomodo** [comment]
It seems that Win32 function `GetFileAttributesEx` cannot handle a relative path with a long path prefix.

Returns false: `NativeMethods.GetFileAttributesEx("\\\\?\\C:qr4bxbzb.k1v-exists", ...`
Returns true: `NativeMethods.GetFileAttributesEx("\\\\?\\C:\\qr4bxbzb.k1v-exists", ...`
Returns true: `NativeMethods.GetFileAttributesEx("C:qr4bxbzb.k1v-exists", ...`

Win32 function `FindFirstFileEx` returns error 123: `ERROR_INVALID_NAME`.

ee8c09c7a8d23c257259017024f70492b6623965

**Comment by Yomodo** [comment]
@warrenlbrown Could you again try with the development build?

**Comment by warrenlbrown** [comment]
Thanks, but still not totally right. Note following, in which the 1st one is not handled correctly.

    Directory \\?\c:\ does not exists
    Directory \\?\c:\temp\ exists
    Directory \\?\c: exists
    Directory c:\ exists
    Directory c:\temp\ exists
    Directory c: exists

**Comment by warrenlbrown** [comment]
Voila !  Looks good with the following tests. Thank you very much.

    Directory \\?\c:\temp\ exists
    Directory \\?\c:\temp exists
    Directory \\?\c:\ exists
    Directory \\?\c: exists
    Directory c:\temp\ exists
    Directory c:\temp exists
    Directory c:\ exists
    Directory c: exists
    Directory \\?\c:\a does not exist
    Directory \\?\c:\a\ does not exist
    Directory c:\a does not exist
    Directory c:\a\ does not exist

**Comment by Yomodo** [comment]
Yes! I think this was the last one.
