### ISSUE TITLE
Alphaleonis.Win32.Network.Host.GetShareInfo doesn't work since 2.1.0

### ISSUE THREAD

**Issue by Schoolmonkey** [alphaleonis/AlphaFS#289]
While the mehtod workes great in 2.0.1, after Upgrade using just 2 params
Host.GetShareInfo Method (String, Boolean),

in 2.1.0 and newer versions I got an Invalid Share Error

System.Net.NetworkInformation.NetworkInformationException (0x80004005): Diese fr
eigegebene Ressource existiert nicht
   bei Alphaleonis.Win32.Network.Host.GetShareInfoCore(ShareInfoLevel shareLevel
, String host, String share, Boolean continueOnException) in D:\Coding\Projects\
GitHub\AlphaFS\AlphaFS\Network\Host Class\ServerMessageBlock.cs:Zeile 383.
   bei Alphaleonis.Win32.Network.Host.GetShareInfo(String uncPath, Boolean conti
nueOnException) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Network\Host Class\
ServerMessageBlock.cs:Zeile 172.

I hope you can help me.
Greetings

**Comment by Yomodo** [comment]
You are 100% sure the share exists?

**Comment by Schoolmonkey** [comment]
@Yomodo 
I think I am. I've tested it with 3 servers using shares, the explorer can find without any problems.
Does it work in your environment? When I use the "Get-WmiObject Win32_share" command in the powershell the share is found as well. (Tested with a Windows Server 2012 R2)

The shares have been in format "\\server\name".

**Comment by v2kiran** [comment]
yup i can confirm that...
@Schoolmonkey  - as a workaround you could use this method which worked for me.

GetShareInfo(
	string host,
	string share,
	bool continueOnException
)

**Comment by damiarnold** [comment]
It would appear that in the GetShareInfo() function overloads with the single string for uncPath, that the uncPath is first processed as:

var unc = GetHostShareFromPath(uncPath);

This function appears to return the host portion (unc[0]) correctly, but the share path portion (unc[1]) returns with a leading backslash.  At this point, it would appear that the leading backslash is correct in the return from GetHostShareFromPath() via the code comments / documentation, however, in looking at older versions of this function it looks like it did *not* return a leading backslash?  This may have changed for Fix #132 with commit 2d5a25b4662d7690efeeba2482be74dc8ecbe66c ?

I can reproduce this issue and subsequent "fix" fairly easily in something like LinqPad, for example:

Broken call (similar to what is in the code today):
var hostShare = Host.GetHostShareFromPath(path);
Host.GetShareInfo(hostShare[0], hostShare[1], false);

Working call:
var hostShare = Host.GetHostShareFromPath(path);
Host.GetShareInfo(hostShare[0], hostShare?[1].TrimStart("\\".ToCharArray()), false);


Anyway, without knowing where to make the appropriate change, and being new to GitHub pull requests, I'm posting a possible solution here.

Hope this helps!
