### ISSUE TITLE
PathTooLongException when component has exactly 255 characters

### ISSUE THREAD

**Issue by pawod** [alphaleonis/AlphaFS#290]
I can't create `DirectoryInfo`s for folders that contain exactly 255 characters, which should be possible as this is the maximum allowed number.

**Not working (255 chars for component with prefix `dir_`):**
`new Alphaleonis.Win32.Filesystem.DirectoryInfo(Path.GetLongPath(@"\\?\UNC\share123.domai.in\RandomNameFoo Baaaaar\3a26705a-094f-43e5-849d-0507b42d0b01\dir_14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_118729a\New folder"))`

**Working (254 chars for component with prefix `dir_`):**
`new Alphaleonis.Win32.Filesystem.DirectoryInfo(Path.GetLongPath(@"\\?\UNC\share123.domai.in\RandomNameFoo Baaaaar\3a26705a-094f-43e5-849d-0507b42d0b01\dir_14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_1187295568005902_4662439486840127202_o14682075_118729\New folder"))`

**Stack Trace:**
`   at Alphaleonis.Win32.Filesystem.Path.NormalizePath(String path, GetFullPathOptions options) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.ValidationAndChecks.cs:line 428
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathCore(KernelTransaction transaction, String path, GetFullPathOptions options) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.GetFullPath.cs:line 241
   at Alphaleonis.Win32.Filesystem.Path.GetExtendedLengthPathCore(KernelTransaction transaction, String sourcePath, PathFormat pathFormat, GetFullPathOptions options) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.ShortLongConversions.cs:line 264
   at Alphaleonis.Win32.Filesystem.FileSystemInfo.InitializeCore(Boolean isFolder, KernelTransaction transaction, String path, PathFormat pathFormat) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\FileSystemInfo.cs:line 206
   at Alphaleonis.Win32.Filesystem.DirectoryInfo..ctor(String path) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\DirectoryInfo Class\DirectoryInfo.cs:line 43`

Is the number of characters per path component calculated correctly? Or did I miss some important detail regarding the characters limit in path components?

**Comment by Yomodo** [comment]
This simple test shows that AlphaFS is capable of creating a folder in the root of the drive, with a name that has a maximum of 255 characters.  `System.IO` however, fails on this.

```
var drive = @"C:\";

// System.IO: 244, anything higher throws System.IO.PathTooLongException.
// AlphaFS  : 255, anything higher throws System.IO.PathTooLongException.
var folder = new string('a', 255);


var local = drive + folder;
var unc = Alphaleonis.Win32.Filesystem.Path.LocalToUnc(local);
Console.WriteLine("Drive length: {0} / Folder length: {1} / Total local length: {2} / Total UNC length: {3}", drive.Length, folder.Length, local.Length, unc.Length);


// Works
var di = new Alphaleonis.Win32.Filesystem.DirectoryInfo(local);

// Works
//var di = new Alphaleonis.Win32.Filesystem.DirectoryInfo(unc);


// Throws System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
//var di = new System.IO.DirectoryInfo(local);


di.Create();
Assert.IsTrue(di.Exists);
```

**Comment by Yomodo** [comment]
Closing issue as there is no feedback.
