### ISSUE TITLE
CopyOptions.CopySymbolicLink not working in 2.1.2

### ISSUE THREAD

**Issue by v2kiran** [alphaleonis/AlphaFS#292]
CopySymbolicLink	2048   COPY_FILE_COPY_SYMLINK
If the source file is a symbolic link, the destination file is also a symbolic link pointing to the same file that the source symbolic link is pointing to.

**Method used**
Copy(
	string sourceFileName,
	string destinationFileName,
	CopyOptions ([Alphaleonis.Win32.Filesystem.CopyOptions]::CopySymbolicLink
)

privilige used: [Alphaleonis.Win32.Security.Privilege]::CreateSymbolicLink

the copy succeeds but the resulting file\folder is not a symboliclink.

tested on windows 10 & server 2012R2

**Comment by Yomodo** [comment]
`CopyOptions.CopySymbolicLink` will also work on directories.
