### ISSUE TITLE
Alphaleonis.Win32.Filesystem.DirectoryInfo Delete($true,$true) does not work properly

### ISSUE THREAD

**Issue by Han63** [alphaleonis/AlphaFS#293]
PS C:\Users\administrator.CONTOSO> $Path = "C:\Folder level 1"
PS C:\Users\administrator.CONTOSO> $dirInfo = New-Object -TypeName Alphaleonis.Win32.Filesystem.DirectoryInfo($Path)

PS C:\Users\administrator.CONTOSO> $dirinfo.Delete($true,$true)
Exception calling "Delete" with "2" argument(s): "(145) The directory is not empty: [\\?\C:\Folder level 1\Folder level
 2\Folder level 3\Folder level 4\Folder level 5\Folder level 6\Folder level 7\Shared Folder\This folders name is looooo
ooooooooooooooooooooooooooong\This folders name is lnog tooooooooooooooooooooooooo]"
At line:1 char:16
+ $dirinfo.Delete <<<< ($true,$true)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Comment by Han63** [comment]
Windows Server 2008 R2 Standard 6.1.7601.65536
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

Folder path:
C:\Folder level 1\Folder level
 2\Folder level 3\Folder level 4\Folder level 5\Folder level 6\Folder level 7\Shared Folder\This folders name is looooo
 ooooooooooooooooooooooooooong\This folders name is lnog tooooooooooooooooooooooooo

Where "Shared Folder" is shared out. The error is misleading and is triggerd if I try to delete the "Folder level 1" folder and everything underneath.
But If I first remove the share no error occurs.

**Comment by Han63** [comment]
Dangerous DLL!
When deleting files on a remote share which are open but NOT locked, the following error is produced:
Exception calling "Delete" with "2" argument(s): "(145) The directory is not empty:
This is a misleading error message.
Furthermore the remaining files are left damaged, when displaying the security tab no information is shown and I'm unable to tak ownership.
This is the code I'm using:

$Folderpath = "\\domain.local\dfs\something\some_Data\Common\dataexchange"
$NotificationSource = "C:\Scripts\EmptyFolderStructure\Some text file.txt"

If (-Not(Get-Module -Name AlphaFS))
{
    Import-Module -Name "C:\Scripts\EmptyFolderStructure\AlphaFS.2.1.2.0\Lib\Net40\AlphaFS.dll"
}

$AllFolders = Get-ChildItem -Path $Folderpath -Directory
ForEach ($Folder in $AllFolders)
{
 Write-Host $Folder.FullName
    $DirectoryInfo = New-Object -TypeName Alphaleonis.Win32.Filesystem.DirectoryInfo($Folder.FullName)
    $DirectoryInfo.Delete($true,$true)
}
Get-ChildItem -Path $Folderpath -File -Force | Remove-Item
Copy-Item -Path $NotificationSource -Destination $Folderpath

**Comment by Yomodo** [comment]
Could you shorten your paths and try again with [System.IO] DirectoryInfo() to see what results you get?
At the moment I'm a short on for extensive testing myself.

**Comment by Yomodo** [comment]
Also, it seems .NET 2.0 is used?
`CLRVersion 2.0.50727.5485`

**Comment by Yomodo** [comment]
Closing issue as there is no feedback.
