### ISSUE TITLE
[Alphaleonis.Win32.Filesystem.Path]::GetFullPath always defaults to the user's home directory

### ISSUE THREAD

**Issue by v2kiran** [alphaleonis/AlphaFS#294]
**public static string GetFullPath(
	string path
)**

**Remarks**
_GetFullPathName merges the name of the current drive and directory with a specified file name to determine the full path and file name of a specified file._

**Issue**
A file named 'test.txt' located at c:\temp should return c:\temp\test.txt but
GetFullPath('test.txt') --> actually returns c:\users\administrator\test.txt 

so the current directory is defaulting to the logged on user's home directory.

version of ALphaFS: 2.1.2

**Comment by Yomodo** [comment]
Do you also experience this with [System.IO.Path]::GetFullPath() ?

**Comment by v2kiran** [comment]
i hadnt tried the system.io.path but did just now and it seems to do the same. Anyway based on the description of getfullpath I expected the method to return the current working directory which would be more useful than the home directory.

**Comment by HugoRoss** [comment]
I tried it out and it works the same (as expected), in AlphaFS and System.IO (never mind that's in VB):

	Imports Alpha = Alphaleonis.Win32.Filesystem
	Imports Sys = System.IO

	Module Module1

		Sub Main()
			'Set the current directory
			Dim myRoot As String = "C:\Temp"
			Environment.CurrentDirectory = myRoot
			'Check with AlphaFS
			Dim myResultAlpha As String = Alpha.Path.GetFullPath("foo\bar")
			Debug.Assert(myResultAlpha = "C:\Temp\foo\bar")
			Debug.Assert(Environment.CurrentDirectory = myRoot, "The current directory may not have changed.")
			'Check with System.IO
			Dim myResultMS As String = Sys.Path.GetFullPath("foo\bar")
			Debug.Assert(myResultMS = "C:\Temp\foo\bar")
			Debug.Assert(Environment.CurrentDirectory = myRoot, "The current directory may not have changed.")
		End Sub

	End Module

So I recommend to close this issue as irreproducible...
