### ISSUE TITLE
File.Copy can't find file that FileInfo can

### ISSUE THREAD

**Issue by ghost** [alphaleonis/AlphaFS#295]
I'm having this issue where I get File Not Found on SOME files, all of which are over 260 chars, including directory.  I decided to see if I could simplify it to debug, so I wrote the snippet below, and the same thing happens.  

```
Imports Alphaleonis

Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim InputLine As String = "C:\shared\Users Shared Folders\Project Management\Project Files 2017\Goldberg-Barnett 15-014\correspondence\Submittal\shop drawings\BBC wall submittals\submittal received 8.14.15\Submittal - 016 00 - Mix design - Wall concrete with color - 03 3000 2 7 PCS REVIEW-1.pdf"
        Dim Destination As String = "Q:\Users Shared Folders\Project Management\Project Files 2017\Goldberg-Barnett 15-014\correspondence\Submittal\shop drawings\BBC wall submittals\submittal received 8.14.15\Submittal - 016 00 - Mix design - Wall concrete with color - 03 3000 2 7 PCS REVIEW-1.pdf"

        Dim info As New Alphaleonis.Win32.Filesystem.FileInfo(InputLine)
        Dim Length = info.Length

        Try
            Alphaleonis.Win32.Filesystem.File.Copy(InputLine, Destination, True, pathFormat:=win32.FileSystem.PathFormat.LongFullPath)
        Catch ex As Exception
            Dim exstring = ex.ToString
            MsgBox(ex.ToString)
        End Try

    End Sub
End Class
```

FileInfo finds the file, and reports the correct size.  
File.Copy reports: 
`"System.IO.DirectoryNotFoundException: (3) The system cannot find the path specified: [C:\shared\Users Shared Folders\Project Management\Project Files 2017\Goldberg-Barnett 15-014\correspondence\Submittal\shop drawings\BBC wall submittals\submittal received 8.14.15\Submittal - 016 00 - Mix design - Wall concrete with color - 03 3000 2 7 PCS REVIEW-1.pdf]" & vbCrLf & "   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\NativeError.cs:line 83" & vbCrLf & "   at Alphaleonis.Win32.Filesystem.File.CopyMoveCore(Boolean isFolder, KernelTransaction transaction, String sourceFileName, String destinationFileName, Boolean preserveDates, Nullable`1 copyOptions, Nullable`1 moveOptions, CopyMoveProgressRoutine progressHandler, Object userProgressData, PathFormat pathFormat) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\File Class\File.CopyMove.cs:line 1170" & vbCrLf & "   at Alphaleonis.Win32.Filesystem.File.Copy(String sourceFileName, String destinationFileName, Boolean overwrite, PathFormat pathFormat) in D:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\File Class\File.CopyMove.cs:line 128" & vbCrLf & "   at alphatest.Form1.Form1_Load(Object sender, EventArgs e) in c:\users\backup\documents\visual studio 2015\Projects\alphatest\alphatest\Form1.vb:line 12"`

**Comment by ghost** [comment]
Environ:
Windows Server 2008 R2 SP1 
VS Express 2015
AlphaFS 2.1.2.0
.NET 4.5

**Comment by Yomodo** [comment]
I think the culprit is: `win32.FileSystem.PathFormat.LongFullPath`
When you specify `win32.FileSystem.PathFormat.LongFullPath`, it is expected that the given
path is already in long path format, which is not the case.

You need to use: `win32.FileSystem.PathFormat.FullPath` here.

**Comment by Yomodo** [comment]
Closing issue as there is no feedback.
