### ISSUE TITLE
Folder rename (casing) throws IOException with HResult 'ERROR_SAME_DRIVE'

### ISSUE THREAD

**Issue by doormalena** [alphaleonis/AlphaFS#296]
When changing the name of a folder from e.g. 'Test' to 'test' an IOException is thrown with a message like: "The system cannot join or substitute a drive to or for a directory on the same drive: [\\?\UNC\server\share\Test]". The default System.IO implementation does work in this scenario.

Used code:
`Directory.Move(currentFullPath, newFullPath);`

Partial stacktrace:
>   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.Directory.CopyMoveCore(KernelTransaction transaction, String sourcePath, String destinationPath, Nullable`1 copyOptions, Nullable`1 moveOptions, CopyMoveProgressRoutine progressHandler, Object userProgressData, PathFormat pathFormat)
RenameDirectory   at Alphaleonis.Win32.Filesystem.Directory.Move(String sourcePath, String destinationPath)

Workaround:
```
try
{
  Directory.Move(currentFullPath, newFullPath);
}
catch(IOException ex) when (ex.HResult == 143)
{
  // Thrown by AlphaFS, try C# default Move instead
  // 143 => ERROR_SAME_DRIVE => The system cannot join or substitute a drive to or for a directory on the same drive.
					
  // Fallback
  System.IO.Directory.Move(currentFullPath, newFullPath);
}
```

**Comment by Yomodo** [comment]
I assume `newFullPath` only contains the new folder name and not the fullpath?

**Comment by doormalena** [comment]
It contains the full path to the new location of the folder, where the only difference with `currentFullPath` is the casing of the last folder name in the path. Would it make a difference when this is changed to only the name of the folder? If so, the behavior is still different from the default .NET implementation.

**Comment by oguimbal** [comment]
+1
