### ISSUE TITLE
Path.GetFullPath(..) throws ArgumentException when used with a pattern

### ISSUE THREAD

**Issue by HugoRoss** [alphaleonis/AlphaFS#300]
Current behavior:
The example below throws a System.ArgumentException: 'Illegal characters: [*] in path.', even though option GetFullPathOptions.CheckAdditional is not specified. 

		string myResult = Path.GetFullPath(".\\bin\\debug\\*.dll");

Expected behavior:
The path is resolved without touching the wildcard characters. In the example above the result would be something like "C:\Source\Scrap\TryOut\bin\debug\*.dll".

Suggested TODOs:
- Fix the bug that only when option GetFullPathOptions.CheckAdditional is specified an exception is thrown
- Add paths with wildcars (* and ?) to UnitTestConstants.InputPaths

**Comment by Yomodo** [comment]
I'm now doubting if this is a BUG, because the default AlphaFS behaviour equals `System.IO`, which is to throw a `System.ArgumentException: Illegal characters`.

**Comment by HugoRoss** [comment]
But what sense makes option GetFullPathOptions.CheckAdditional in that case? It is especially made for throwing an exception in case a "*" or "?" is within the string.

**Comment by Yomodo** [comment]
Correct, it is used only internally so that path verification is done, as much as possible, in the same way as `System.IO` does.

**Comment by Yomodo** [comment]
@HugoRoss Is it OK if I close this issue?

**Comment by Yomodo** [comment]
Closing issue as there is no feedback.

**Comment by HugoRoss** [comment]
Commented 8th of January the following through email-reply:

I would still see the benefit of having it implemented even if you don't classify it as a bug - but I mean it's your project and your time, I gonna respect your decision. If it is a question of time alone, I think you could convince me to write an implementation.

**Comment by Yomodo** [comment]
Sorry, I did not got any e-mail through GitHub.

Yes, most of the time it is a lack of time and a bit of personal priorities.
And no, AlphaFS is for everyone who wants to improve upon. ;)

Having a working implementation can of course help a lot, so if you still feel challenged...
