### ISSUE TITLE
Path.Constants.cs: Don't use CurrentCulture

### ISSUE THREAD

**Issue by HugoRoss** [alphaleonis/AlphaFS#303]
Path.Constants.cs:

Using CultureInfo.CurrentCulture to assign the string of a static readonly field means, that the first thread accessing the Path class determines the culture that is used and that remains for all other threads during the lifetime of the application.

If there are differences between calls to ToString(..) with different CultureInfos that needs to be taken into account (which I don't hope), then the fields must be implemented as properties and cannot be cached (not even ThreadStatic as one thread can easily change its current culture), otherwise use CultureInfo.InvariantCulture to get a guaranteed consistent result.

**Comment by Yomodo** [comment]
True, I have already run into issues with CurrentCulture in other projects.
For file paths InvariantCulture seems to be the best setting.

**Comment by damiarnold** [comment]
+1
