### ISSUE TITLE
Contribution guideline updates for indentation / spacing

### ISSUE THREAD

**Issue by damiarnold** [alphaleonis/AlphaFS#307]
In looking at the Contribution Guidelines listed on the AlphaFS GitHub Wiki page, I didn't see anything mentioning the correct indentation / spacing considerations.  However, in reviewing the project code itself, it would appear that it makes use of a 3 space indentation style.

1.  Could the contrib docs be updated to state what the spacing / indentation should be? (e.g. spaces vs tabs, tab width / number of spaces, etc.)

2.  It appears that VS 2017 will support [EditorConfig](http://editorconfig.org/) (see http://editorconfig.org and https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/ natively, which looks like it will bring nice support for adjusting the IDE style settings dynamically per-solution or even per-project.  Adding an **.editorconfig** file to the solution may be useful for those who default to a different standard, and currently need to keep changing the editor environment before modifying code for possible pull request.

**Comment by alphaleonis** [comment]
Thanks for pointing this out. I have updated the wiki, and will add an `.editorconfig`. Didn't know VS2017 supported this.  Good idea!
