### ISSUE TITLE
Renaming Folders with Trailing Space

### ISSUE THREAD

**Issue by myGit0815** [alphaleonis/AlphaFS#308]
Even with using the latest Version of AlphaFS I am still running into Problems with trailing Spaces in Foldernames. I would like to rename them, not delete them.

My Powershell Sourcecode looks like this:
```Powershell
$basePath = "\\?\UNC\servername\sharename"
$allFilesAndFolders = [Alphaleonis.Win32.Filesystem.Directory]::EnumerateFileSystemEntries($basePath, '*', [System.IO.SearchOption]::AllDirectories)
foreach($fileOrFolder in $allFilesAndFolders) {
	if($fileOrFolder -like "* " -or $fileOrFolder -like "*.") {
		$newFileOrFolder = $fileOrFolder.TrimEnd(" ", ".")
		[Alphaleonis.Win32.Filesystem.Directory]::Move($fileOrFolder, $newFileOrFolder)
	}
}
```

With this Code I still get a "Path not found" exception. How can I get around this? Is there another way than movinging the folder?

**Comment by Yomodo** [comment]
Please take a peek here: https://github.com/alphaleonis/AlphaFS/wiki/PowerShell
And search for: "trailing space"
The magic lies in the use of: `[Alphaleonis.Win32.Filesystem.PathFormat]::FullPath`

**Comment by myGit0815** [comment]
Works like a charm! Thanks for the quick response, Problem is solved.
Sorry for not seeing that.
