### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by roman-himmelreich-sp** [alphaleonis/AlphaFS#310]
Hi guys,
How do I create a pull request?
I get access denied when trying to publish a new branch...

I have added support for querying 'GetFileInformationByHandleEx' with 'FileInfoByHandleClass.FileAttributeTagInfo'.
Also added a method to the 'File' class: 'GetReparsePointTag' this is really helpful when querying 'GetFileInformationByHandleEx' with a result structure that does not include 'ReparsePointTag'

**Comment by alphaleonis** [comment]
You need to fork the project first, since you do not have write-access to this repo.  Then make the changes to your local project and create a pull request from there.
