### ISSUE TITLE
Appending a line break with AppendAllText?

### ISSUE THREAD

**Issue by GerRudi** [alphaleonis/AlphaFS#316]
[Question] Is there currently a method to append a line break with AppendAllText?
(Using AlphaFS 2.1 with .Net 4.5 in Powershell)

I'm trying to use **File.AppendAllText Method (String, String, Encoding, PathFormat)** to write logs into a file.

However, I wasn't able to find a solution to add a linebreak. The  "`n" isn't working and I couldn't find another solution, not with unicode characters or anything.

I imagine that File.AppendAllLines is capable of doing this, but I'd like to avoid creating an enum for a single line of text each.

Sample code
`       [Alphaleonis.Win32.Filesystem.File]::AppendAllText("$logdir\log$executiontime.log",  "$($timestamp): $message",[System.Text.Encoding]::UTF8, [Alphaleonis.Win32.Filesystem.PathFormat]::FullPath)`

**Comment by Yomodo** [comment]
Have you tried adding `Environment.Newline` to the end of your string?

**Comment by GerRudi** [comment]
I'm sorry, it was my mistake. :(

I forgot that Windows Notepad requires CRLF as a new line.
In case anyone else stumbles upon this issue:

**\`r\`n**
 = new line

Thanks for your response and the great work.
