### ISSUE TITLE
Get-longChild items from root of share

### ISSUE THREAD

**Issue by Andreyspro** [alphaleonis/AlphaFS#319]
Hellow.
Im try get-longchilditems from networkshare \\s01-storage1\temp:
![1](https://cloud.githubusercontent.com/assets/28852205/26290964/c2fcf004-3edd-11e7-8ce6-006c436506c5.png)

This function retun me only 1 "Directory" object - input directory:
![3](https://cloud.githubusercontent.com/assets/28852205/26291013/0845c046-3ede-11e7-81ec-6a6b20e35c54.png)

However, standart funtion work fine:
![2](https://cloud.githubusercontent.com/assets/28852205/26291033/21dcc284-3ede-11e7-9b7a-0406dc7c9691.png)

If im try get child from next level directory (\\s01-storage1\temp\SQLIO), alphaFS function work fine:
![4](https://cloud.githubusercontent.com/assets/28852205/26291078/6feeca76-3ede-11e7-88f4-d226743cd5a0.png)

.NET Alphaleonis function wrok fine, when i try get childs from \\s01-storage1\temp:
![5](https://cloud.githubusercontent.com/assets/28852205/26291137/d5fbd458-3ede-11e7-9312-b573b0265ea7.png)

Get-LongChildItems work wrong with shares, please help me.

**Comment by Andreyspro** [comment]
Server version Windows 2012 R2.

**Comment by Yomodo** [comment]
We did not create the Get-LongChildItems cmdlet.

**Comment by raandree** [comment]
Check out Get-ChildItem2 provided via https://github.com/raandree/NTFSSecurity. This module uses AlphaFS as well.
