### ISSUE TITLE
Search files/folders using multiple filters.

### ISSUE THREAD

**Issue by daisy613** [alphaleonis/AlphaFS#322]
Is it possible to specify multiple search strings in the EnumerateFileSystemEntryInfos method?  Let's say I'm looking for files with several different extensions.  I am using the script written by http://powershell-guru.com/fastest-powershell-2-count-all-files-in-large-network-share/.  I am trying to come up with something that works faster and more reliably than gci -include $extensions

**Comment by Yomodo** [comment]
Unfortunately this is not possible.

**Comment by Yomodo** [comment]
Also, AlphaFS has built-in support for this using the method: [Directory.GetProperties()](http://alphafs.alphaleonis.com/doc/2.1/api/html/782613ED.htm)

	Aggregated properties of file system objects from Directory: [C:\Windows]

		#001	Archive           = [111112]
		#002	Compressed        = [9739]
		#003	Device            = [0]
		#004	Directory         = [28499]
		#005	Encrypted         = [0]
		#006	Hidden            = [2175]
		#007	IntegrityStream   = [0]
		#008	Normal            = [11193]
		#009	NoScrubData       = [0]
		#010	NotContentIndexed = [68]
		#011	Offline           = [0]
		#012	ReadOnly          = [6443]
		#013	ReparsePoint      = [0]
		#014	SparseFile        = [0]
		#015	System            = [481]
		#016	Temporary         = [1]
		#017	File              = [122333]
		#018	Total             = [150832]
		#019	Size              = [27247520170]

		*Duration: [3562] ms. (00:00:03.5620469) [18: There are no more files]
