### ISSUE TITLE
Several instances of ArgumentException.ParamName not set/used correctly

### ISSUE THREAD

**Issue by elgonzo** [alphaleonis/AlphaFS#328]
I noticed that in several places AlphaFS is throwing ArgumentExceptions with the ParamName argument/property set incorrectly.

Sometimes, AlphaFS passes the parameter value instead of the parameter name for the ParamName argument when creating an ArgumentException, which look like oversights and should be rather easy to fix, i guess.

However, there are also places (like in the [DirectoryInfo.CreateSubdirectoryCore](https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS/Filesystem/DirectoryInfo%20Class/DirectoryInfo.CreateSubdirectory.cs#L162) or [Path.CheckInvalidPathChars](https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS/Filesystem/Path%20Class/Path.ValidationAndChecks.cs#L199) method) where the code is misusing the ParamName argument to channel some other information (some intermediate processing result) through the exception. Not sure if these are cases of oversight too, or whether there was an intention behind doing so (whatever the reason, that's not what the ParamName argument is for...)

**Comment by Yomodo** [comment]
.NET itself uses the `ArgumentException` with explanatory text where the parameter name is used
most of the time.

The expectation was to see only the parameter name instead of its value?

**Comment by elgonzo** [comment]
Can you show me an example where .NET uses the ParamName argument to carry anything but the *name* of the problematic argument/parameter?

Note that the argument is called "ParamName", not "ParamValue". Also look at the message composed by the ArgumentException when you set the ParamName argument -- it also speaks about "parameter name", not "parameter value"...

And finally, i let the MSDN documentation [for ArgumentException.ParamName](https://msdn.microsoft.com/en-us/library/system.argumentexception.paramname(v=vs.110).aspx) speak for itself:

> Gets the _**name**_ of the parameter that causes this exception.

(emphasis mine)

**Comment by Yomodo** [comment]
This is where I looked:

http://referencesource.microsoft.com/#mscorlib/system/argumentexception.cs,109b3ef6299ef9df,references

**Comment by elgonzo** [comment]
Yes, the reference source just confirms everything i said.
How/where did the reference source give you the idea that "ParamName" does not mean parameter name, but parameter value?

**Comment by Yomodo** [comment]
I get it, instead of: `throw new ArgumentException(Resources.Invalid_Subpath, pathLp);`

it should be: `throw new ArgumentException(Resources.Invalid_Subpath, `**"pathLp"**`);`

This is obviously a bug, thanks!

**Comment by elgonzo** [comment]
Hold on :)

Actually it should not be "pathLp".
Note that pathLp is a variable internal to the method. You should use the name of the method argument that is responsible for causing the ArgumentException (in this case "path", i think).

By the way, i have fixed this issue already on my local fork. I will make a pull-request in a few minutes, should make it easier for you, i hope :)
