### ISSUE TITLE
Rename method File/Directory.TransferTimestamps to CopyTimestamps.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#331]
The method copies the timestamps, as in copy items from A to B.
Using the word transfer implies a move of items from A to B, which is not the case.

**Comment by alphaleonis** [comment]
Suggestion: Leave the old methods as well, just as aliases for the new names, and tag them with the ObsoleteAttribute with a mesage pointing to the new names. (Will generate a compiler warning if they are used, which is a bit "nicer" than just removing them. ;)

**Comment by Yomodo** [comment]
Way more civilized yeah.
