### ISSUE TITLE
Win32.FileSystem.Path validation not handling alternate stream paths correctly

### ISSUE THREAD

**Issue by anevilyak** [alphaleonis/AlphaFS#332]
Path.CheckSupportedPathFormat() looks to see if the input path contains any ':' characters after the second byte of the path, and if so, throws an unsupported exception. Unless there's a supported alternative format that I'm not seeing, this effectively prevents one from opening an alternate data stream using the standard Win32 filename:streamname:$DATA syntax via e.g. File.Copy(). This behavior was observed with version 2.1.2.

**Comment by Yomodo** [comment]
Have a look here: [AlternateDataStreamInfo](http://alphafs.alphaleonis.com/doc/2.1/api/html/512B8CD5.htm)

These methods exist:
`File.EnumerateAlternateDataStreams Method`
`Directory.EnumerateAlternateDataStreams`

**Comment by Yomodo** [comment]
Also, to bypass `Path.CheckSupportedPathFormat()`, specify the `PathFormat.LongFullPath`.
This will use the path as-is.

**Comment by anevilyak** [comment]
The enumeration methods work fine for me. The problem I'm encountering involves trying to copy a stream's content elsewhere via File.Copy. The LongFullPath option does not appear to bypass the check I'm hitting; at least on 2.1.2, https://github.com/alphaleonis/AlphaFS/blob/v2.1.2/AlphaFS/Filesystem/File%20Class/File.CopyMove.cs#L1075 is called regardless, and the latter checks for additional ':' characters in the path unconditionally at https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS/Filesystem/Path%20Class/Path.ValidationAndChecks.cs#L149 . Is there an alternative methodology I'd want to use here?

**Comment by Yomodo** [comment]
I see, the v2.12 implementation of `CopyMoveCore` does not support streams so `LongFullPath` indeed has no effect.

You can take a look at the unit tests `File_EnumerateAlternateDataStreams_LocalAndNetwork` and [`Directory_EnumerateAlternateDataStreams_LocalAndNetwork`](https://github.com/alphaleonis/AlphaFS/blob/master/AlphaFS.UnitTest/Directory%20Class/AlphaFS_Directory_EnumerateAlternateDataStreams.cs#L47)
where streams are read/write using [`File.ReadAllLines`](https://github.com/alphaleonis/AlphaFS/blob/master/AlphaFS.UnitTest/Directory%20Class/AlphaFS_Directory_EnumerateAlternateDataStreams.cs#L101), `File.WriteAllLines` and `File.WriteAllText`

**Comment by anevilyak** [comment]
Will do that, thanks for the quick response! Will this kind of operation be supported more directly in a future release?

**Comment by Yomodo** [comment]
If I'm correct, the current most direct way is to use a combination of `File.Open` and `File.Write` with the `Path.StreamSeparator` in the path.  So these could easily be your own local helper functions.

**Comment by Yomodo** [comment]
On a final note, there's also the [BackupFileStream](https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS.UnitTest/Classes/AlphaFS_BackupFileStream.cs) class to copy streams.

**Comment by anevilyak** [comment]
Sounds good, thanks again, and keep up the good work!
