### ISSUE TITLE
Most Privilege constants were removed

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#334]
This is a major breaking change, without any good cause. Since these are public there is no way of knowing that they are "Unused". Also the Backup privilege is referenced by XML-Doc comments, so the removal of this caused warnings to appear during build.

The privilege definitions should be left in, since these are quite useful, even though not all of them are useful for file operations per-se, it seems like a good idea to leave them in, especially since removing them would be a breaking change.

Applies to the develop branch. Changes were made in commit d70416b5

**Comment by alphaleonis** [comment]
Out of curiosity, why was this reopened @Yomodo?

**Comment by Yomodo** [comment]
No particular reason, I've must have clicked a bit too much.
