### ISSUE TITLE
AlphaFS doesn't imported

### ISSUE THREAD

**Issue by liho26** [alphaleonis/AlphaFS#346]
Hi. I imported module with Import-Module -Name "C:\Program Files\WindowsPowerShell\Modules\PSAlphaFS\2.0.0.1\lib\Net45\AlphaFS.dll" command.

I try to use Get-LongChildItem and Rename-LongItem commands. and I get error with message: 

Get-LongChildItem : The 'Get-LongChildItem' command was found in the module 'PSAlphaFS', but the module could not be loaded. For more information,  run 'Import-Module PSAlphaFS'.

What I doing wrong?

**Comment by Yomodo** [comment]
This is only PSAlphaFS related, which is not ours.

**Comment by liho26** [comment]
Ok, Thank you for answer.
