### ISSUE TITLE
File.GetFileSystemEntryInfoCore should throw Directory/FileNotFoundException, depending on isFolder argument.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#349]
Use case:

Get a directory: `File.GetFileSystemEntryInfoCore` is called and the `isFolder` argument is set to `true`.
However, if the directory does not exist, but a file with the same name exists, that file is returned.

This behaviour **is only correct** when the argument `ContinueOnException` is set to `true`.

If `ContinueOnException` is set to `false`, the applicable `DirectoryNotFoundException` or `FileNotFoundException` should be thrown.

**Comment by Yomodo** [comment]
Please note that this will **break** if you are currently using **`File.GetFileSystemEntryInfo`** for directories.
These methods calls must be changed to: **`Directory.GetFileSystemEntryInfo`**

**Comment by Lupinho** [comment]
I am completely unhappy with this change. So how can I get a FileSystemEntryInfo that can be a file or a folder? And how can I detect, if a path should belong to a file or folder??
