### ISSUE TITLE
Why is there no DirectoryNotFoundException in AlphaFS?

### ISSUE THREAD

**Issue by kabaur** [alphaleonis/AlphaFS#359]
An Implementation of `DirectoryNotFoundException` is missing in:
AlphaFS/AlphaFS/Filesystem/Exceptions/ 
At the moment I'm using 
`throw new System.IO.DirectoryNotFoundException`
in my Program. I should't get into trouble with this, right? 
Am I missing something or is there any reason for this?
("The day has only 24hours." is a perfectly reasonable answer ;-) )

Thanks.

**Comment by Yomodo** [comment]
The simple reason: `System.IO.DirectoryNotFoundException` already exists.

**Comment by kabaur** [comment]
Ah, got it. Just stumbled over your project today and thought your goal was to override the System.IO completely. Don't ask me why...
Great Work by thy way!
