### ISSUE TITLE
I have problem copy files with special charates in name

### ISSUE THREAD

**Issue by eldonfsr** [alphaleonis/AlphaFS#362]
I have a program for test long names in folder if the file don't has ", & ! " another special characters just
name in 8 characters can validate and copy this a example.
ofile = "C:\\Users\\kike\\Downloads\\5.0 in a Nutshell, 5th Edition.pdf"

always sad no existe the file
 if ( Alphaleonis.Win32.Filesystem.File.Exists(ofile))
   { 
           Alphaleonis.Win32.Filesystem.File.Copy(ofile, nfile, true);
    }
how i can copy this kind of files.

**Comment by ghost** [comment]
Hi,
I have a similar problem : when I use Get-Item2 or Get-ChildItem2 for items in a directory with file/directory names using non ASCII characters (like é or à) they are replaced by "?" in the name.

Is there a way to force this commandlets to use UTF8/16 when retrieving the file/directory info ?

**Comment by Yomodo** [comment]
@eldonfsr If System.IO cannot copy the file because of special characters, then the same will probably also apply to AlphaFS.

@KarimKanounGit AlphaFS does not come with PowerShell cmdlets.

**Comment by Yomodo** [comment]
Further testing shows that AlphaFS has no issues with unicode characters.

Folders/files with names like: `Directory-túd0cásp.iév`, `File-xë0üj0df.hrf`  cause no problems.
