### ISSUE TITLE
How to actually access WPD after Device.EnumerateDevices?

### ISSUE THREAD

**Issue by anothertal3** [alphaleonis/AlphaFS#366]
Hello,

I just stumbled upon this promising package and I'm currently fiddling around with it.

There's an option to enumerate through "Devices" which enables you to detect mobile phones and similar Windows Portable Devices.

Which steps are then necessary to access the device file system?

I tried to create Directory/-Info or Volume/-Info objects using the different paths of the DeviceInfo object but was unsuccessful...

Many thanks in advance!
tale

**Comment by Yomodo** [comment]
Hi, WPD is currently not implemented yet in AlphaFS. It is on the todo.

**Comment by anothertal3** [comment]
Hi Yomodo,

ah, that's a pity. 

I've yet to find a well-documented .NET-WPD-library and I was quite happy when I saw the Devices here in AlphaFS.

Thanks for the information, will be waiting for it then.

tale
