### ISSUE TITLE
Path.Combine() does not work correctly when the first argument is the root of a local drive.

### ISSUE THREAD

**Issue by anevilyak** [alphaleonis/AlphaFS#368]
With AlphaFS 2.1.3, if one calls Path.Combine() with arguments such as: Path.Combine("E:", "file1.txt"), the outcome is E:file1.txt rather than E:\file1.txt. This does not occur if a subfolder is specified, i.e. if the first argument is E:\ADirectory, the result is E:\ADirectory\file1.txt as expected.

**Comment by Yomodo** [comment]
Does System.IO.Path.Combine() give the same results?

**Comment by anevilyak** [comment]
Interesting. It does. Mea culpa, I'd never run into that before.
