### ISSUE TITLE
Directory.EnumerateFileSystemEntryInfos does not return subdirectories with spaces as name.

### ISSUE THREAD

**Issue by Lupinho** [alphaleonis/AlphaFS#369]
Test:
1. Create a subdirectory with name " ".
2. Call Directory.EnumerateFileSystemEntryInfos for the parent directory
The " "-directory will not be enumerated correctly.
The bug is located in the method "private T NewFileSystemEntryType<T>(bool isFolder, NativeMethods.WIN32_FIND_DATA win32FindData, string fileName, string pathLp)", where the behaviour is explicitely programmed - for an unkown reason:
var fullPathLp = (IsRelativePath ? OriginalInputPath + Path.DirectorySeparator : pathLp) + (!Utils.IsNullOrWhiteSpace(fileName) ? fileName : string.Empty);
I know, that a directory " " is somewhat named illegal, but you can create one with AlphaFS easily. Maybe, this wrong handling is programmed in other methods too (e.g. in File.CreateFileCore). I would appreciate a solution of this issue.

**Comment by Yomodo** [comment]
As far as I can test at the moment, as a temp alternative, this works OK:
`var fullPathLp = (IsRelativePath ? OriginalInputPath + Path.DirectorySeparator : pathLp) + fileName;`
