### ISSUE TITLE
Relative path from a full path

### ISSUE THREAD

**Issue by qbprog** [alphaleonis/AlphaFS#370]
Hello,
I could not find a way to obtain the relative path of a full path. For instance,
`Path1` : C:\Windows\Test.txt 
`Path2` : C:\Windows\
something like 
`Path3` = GetRelativePath(Path1,Path2)
`Path3` = ".\Test.txt"

or 
`Path1` = C:\Windows\System\Test.txt
`Path2` = C:\Windows\Other\Directory\
`Path3` = ..\\..\\System\Test.txt

Any ideas?

**Comment by Yomodo** [comment]
Hi, There is no support for that in AlphaFS.
Perhaps this link can help you out: [Combine and resolve relative paths in C#](http://csharphelper.com/blog/2014/08/combine-and-resolve-relative-paths-in-c/)

**Comment by qbprog** [comment]
Actually I'd like to do something like this:
https://stackoverflow.com/questions/13266756/absolute-to-relative-path

could it be a nice feature addon?
