### ISSUE TITLE
What is the expected result of Path.LocalToUnc() ?

### ISSUE THREAD

**Issue by damiarnold** [alphaleonis/AlphaFS#375]
For truly local paths, e.g.  c:\windows, the `Path.LocalToUnc()` call works as documented.
However, when using a mapped drive, such as `W:` mapped to `\\server.test.lab\share1`, if a call is made such as `Path.LocalToUnc("W:\\subpath")` the call returns `\\server.test.lab\share1` instead of `\\server.test.lab\share1\subpath`.   

Is this the expected behavior?  The docs may be a little vague where it states:
`If a logical drive points to a network share path, the share path will be returned instead.`   Does this mean it returns the network share "root" path, or the full network path with the subpath included?

One other point of consideration, when calling `Path.LocalToUnc("W:\\subpath", true)`, the returned path is `\\server.test.lab\share1` instead of `\\?\UNC\server.test.lab\share1` as would be expected for Long Paths. (#376)

**Comment by Yomodo** [comment]
It should return the full network path with the subpath included: `\\server.test.lab\share1\subpath`

This is also what you expected, right?

**Comment by damiarnold** [comment]
I would expect the same.  The commit seems to address the problem as expected.  Thanks!
