### ISSUE TITLE
Path.LocalToUnc() isn't handling trailing directory separators for mapped drives

### ISSUE THREAD

**Issue by damiarnold** [alphaleonis/AlphaFS#379]
Specifying `Path.LocalToUnc("W:\\subpath", false, true, false)` returns `\\server\share\subpath` (if W: maps to \\server\share) without adding the trailing directory separator.  The inverse is also happening, if a separator is included at the end of a mapped drive path with the call to remove it:
`Path.LocalToUnc("W:\\subpath\\", false, false, true)` returns `\\server\share\subpath\`.

These parameters do seem to work with actual local paths (non-mapped local drives).

This behavior is occurring in 2.1.3 as well as the `develop` branch as of commit [2437105](https://github.com/alphaleonis/AlphaFS/commit/2437105a08537c188b86396966eb32be749945c1).

On a tangential note, would it be better served having the signature for `Path.LocalToUnc(string, bool, bool, bool)` replaced with a signature such as `Path.LocalToUnc(string, bool, DirectorySeparatorHandling)` where `DirectorySeparatorHandling` could be an enum such as:

`enum DirectorySeparatorHandling
{
    None = 0,
    RemoveTrailingSeparator =1,
    AddTrailingSeparator = 2
}`

I ask this simply because it is non-determinate from just reading the code what the output would be when both trailing separator booleans are set to true, without actually running the code.  Essentially, it looks like I can set two mutually exclusive options at the same time.  Right now, when both are set to true, it looks like the "remove trailing separator" logic wins out.  Just a thought. :-)

**Comment by Yomodo** [comment]
Yeah, not the "brightest" of method signatures.. will look into this.

**Comment by Yomodo** [comment]
Instead of introducing an `DirectorySeparatorHandling` enum, we'll apply the [GetFullPathOptions](https://github.com/alphaleonis/AlphaFS/blob/f59b649327af60bbfaed3d06e6618f991863d848/AlphaFS/Filesystem/Structures%20And%20Enumerations/GetFullPathOptions.cs) enum.

The current method will be **replaced** with this one:

    public static string LocalToUnc(string localPath, GetFullPathOptions fullPathOptions)
    {
      return LocalToUncCore(localPath, fullPathOptions);
    }
