### ISSUE TITLE
What is the expected behavior for Path.LocalToUnc() with substitute drive letters?

### ISSUE THREAD

**Issue by damiarnold** [alphaleonis/AlphaFS#380]
When using the **subst** command to map substitute drive letters to other paths, what is the expected behavior?
For the following mappings, here is what I currently get:
W: -> network mapped to `\\server\share`
J:  ->  subst mapped to W:\subpath
K: ->  subst mapped to C:\users\dave  on workstation `workstation`

`Path.LocalToUnc("W:\\subpath", true)` -> correctly returns `\\?\UNC\server\share\subpath` (as of commit [2437105](https://github.com/alphaleonis/AlphaFS/commit/2437105a08537c188b86396966eb32be749945c1)).

`Path.ToLocalUnc("J:\\subpath2", true)` -> returns `\\?\UNC\workstation\J$\subpath2` even though this is not on the local workstation at all

`Path.ToLocalUnc("K:\\Documents", true)` -> returns `\\?\UNC\workstation\K$\Documents` even though there is no share K$ on the local workstation (it is only a substitute drive mapping)

I supposed similar questions / considerations for non-standard path mappings, such as a drive letter mapped to a virtual file system backed by FTP or WebDav, for example, could also fall into this general category of unknown expectations as well.

It may be that the caller is responsible to verify any "local" path / drive letter before making this call, in which case, maybe an addition to the API docs could call this out?  I'm personally fine with this, but knowing how I've seen some people blindly use APIs, a simple warning may be warranted.  :-)

Thanks for the consideration!

**Comment by Yomodo** [comment]
I found an old article regarding this: [SUBST.EXE mapping to share, also considered a UNC share?](http://alphafs.codeplex.com/discussions/316583)

In short: A subst pointing to an UNC path is considered to be an invalid network drive.


> To map a drive letter to a UNC path, one would do something like:
> 
> NET.EXE USE Y: \\server\share
> 
> (DosDeviceName; = "\Device\LanmanRedirector\;Y:000000000002de2c\server\share")
> 
> The same can be achieved by using:
> 
> SUBST.EXE USE Z: \\server\share
> 
> (DosDeviceName; = "\??\UNC\server\share")
> 
> 
> Even the .NET DriveType enum reports drive Z: as a Network drive.
> 
> 
> However, WNetGetUniversalName() seems to choke on this: ERROR_NO_NET_OR_BAD_PATH = 1203
> Deleting the subst using NET.EXE /d will also report that no network drive can be found.
> 
> The AlphaFS implementation of the DriveInfo class supports unc shares/paths and thus has
> the "IsUnc" property, for your convenience, which is not native to .NET.
> 
> Based on the aforementioned, a clear decision should be made to get a true value.
> So, should we consider mappings created by SUBST.EXE, as true UNC mappings?
> 
> The answer is: no



You can create an AlphaFS `DriveInfo` instance to see what you're dealing with:

    Input Drive Path: [C]

	Instance: [Alphaleonis.Win32.Filesystem.DriveInfo]

	#001	AvailableFreeSpace    = [19992690688]
	#002	DiskSpaceInfo         = [C:\]
	#003	DosDeviceName         = [C:]
	#004	DriveFormat           = [NTFS]
	#005	DriveType             = [Fixed]
	#006	IsDosDeviceSubstitute = [False]
	#007	IsReady               = [True]
	#008	IsUnc                 = [False]
	#009	IsVolume              = [True]
	#010	Name                  = [C:\]
	#011	RootDirectory         = [C:\]
	#012	TotalFreeSpace        = [19992690688]
	#013	TotalSize             = [96079966208]
	#014	VolumeInfo            = [\\?\Volume{657d4f85-1da2-478a-946a-318c99706878}\]
	#015	VolumeLabel           = [System]


I haven't tried anything with FTP or WebDav, so there may be some issues there as well...

**Comment by damiarnold** [comment]
Ahh...good to know this was already discussed.  Is it worth referencing any of this info in the various AlphaFS API docs where local paths / drive mappings are passed as parameters?

**Comment by Yomodo** [comment]
It seems that only method: `GetRemoteNameInfoCore` has that remark:

> AlphaFS regards network drives created using SUBST.EXE as invalid.

which of course nobody would see because it's internal. :)

Additional documentation is always a good thing, but I'm not sure if it is handy to mention
this to all methods, as there are quite a number of methods that accept local paths/drive mappings...

**Comment by damiarnold** [comment]
For sure...maybe a sectional reference at a higher level that covers broader considerations, especially for extended functionality that is unique to AlphaFS?  Thanks again for the help.
