### ISSUE TITLE
Release next version (2.2)

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#383]
This release is long overdue it seems.
@Yomodo can we collect what issues needs to be fixed for this release and tag them with the Release 2.2 tag?  

I just noticed several unit tests failing when I ran them, not sure why this is, are you aware of any failing tests?

**Comment by Yomodo** [comment]
I don't have any failing unit test on my side. Windows 10 and Server 2012R2.

**Comment by Yomodo** [comment]
All related Issues have been tagged with Release 2.2

**Comment by Yomodo** [comment]
I now also get failing unit tests, most of them from `Directory/File.Copy/Mode/Delete`,
They surfaced when I plugged in a bunch of USB drives/sticks to test.

This has to do with issue #340 and it seems I did not update the unit tests to reflect this change.

**Comment by alphaleonis** [comment]
Okay, so I get a bunch of Directory and File tests that fail on network tests, with a Caught UNEXPECTED exception [DeviceNotReadyException]. I'm guessing this is some environmental issue.

Then `AlphaFS_Volume_EnumerateVolumes` failes with a DirectoryNotFoundException.
`AlphaFS_Shell32Info_GetVerbCommand_LocalAndNetwork_Success` fails because I don't have .txt files associated with notepad.exe.

`AlphaFS_File_GetProcessForFileLock_LocalAndNetwork_Success` fails for unknown reason. Haven't investigated thoroughly but it fails on the Assert.IsTrue that wants the processname to start with QTAgent or vstext.executionengine.

**Comment by alphaleonis** [comment]
Fixed the `AlphaFS_File_GetProcessForFileLock_LocalAndNetwork_Success`. See recent pull request #393.

**Comment by Yomodo** [comment]
All failing `Directory/File.Copy/Mode/Delete` unit test are fixed.
I don't have any other tests failing.

**Comment by Yomodo** [comment]
I think we're good to go.

**Comment by CyberSinh** [comment]
Great! When do you plan to release AlphaFS 2.2 as NuGet package? Thanks.

**Comment by alphaleonis** [comment]
@Yomodo Will you create a new release-branch and push it once you're satisfied that we are good for a release?  Then I can take care of the actual release process if you want.

**Comment by Yomodo** [comment]
Created a branch and a pull.

**Comment by warrenlbrown** [comment]
Any chance that long-standing problems in #288 will be addressed for 2.2?  Thank you.

**Comment by Yomodo** [comment]
Unfortunately this won't make it into this v2.2 release.

**Comment by Yomodo** [comment]
@warrenlbrown I think I was able to resolve this. You can try it with the current develop version.

**Comment by warrenlbrown** [comment]
Thank you very much. I am out of the office this week, but will plan to test with latest dev version early next week.

**Comment by Yomodo** [comment]
@alphaleonis Any idea when we can release v2.2?

**Comment by alphaleonis** [comment]
@Yomodo Yes, now I have an idea... about now actually. :P   2.2 has been released. I also created a page containing information about how I went about doing the release for future reference. https://github.com/alphaleonis/AlphaFS/wiki/Create-a-new-release
