### ISSUE TITLE
Correct applied fileSystemRights operator in method File.Create().

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#385]
https://github.com/alphaleonis/AlphaFS/blob/c674476bfa01682018460f56a20f69ed6d8f6cb7/AlphaFS/Filesystem/File%20Class/File.Create.cs#L382

@alphaleonis 
I'm a bit confused, shouldn't this read: `fileSystemRights |= FileSystemRights.AppendData;`

    // fileSystemRights will be replaced with: AppendData
    fileSystemRights = FileSystemRights.Write
    fileSystemRights &= FileSystemRights.AppendData

    // fileSystemRights remains: Write (Because It already contains AppendData)
    fileSystemRights = FileSystemRights.Write
    fileSystemRights |= FileSystemRights.AppendData

**Comment by alphaleonis** [comment]
Hm... yes, that indeed looks quite odd.  Haven't had time to look too closely at it yet though. Can we produce a unit-test where this causes an error? Seems like this should create some errors?

**Comment by Yomodo** [comment]
The error that could occur, is that the `fileSystemRights` will always be set to `FileSystemRights.AppendData`, thus overwriting the intial, supplied, value.
