### ISSUE TITLE
Update header in solution files, CHANGELOG.md.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#389]

**Comment by alphaleonis** [comment]
Sorry for asking what is probably a dumb question, but what header in what files? ;)

**Comment by Yomodo** [comment]
:) I'm referring to this line:
`/*  Copyright (C) 2008-2017 Peter Palotas, Jeffrey Jangli, Alexandr Normuradov`

**Comment by alphaleonis** [comment]
Ah, hehe, of course. :)

**Comment by alphaleonis** [comment]
Completed.
