### ISSUE TITLE
Add overloaded methods that use enumerating to support the DirectoryEnumerationFilters argument.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#390]
Enumerating folders/files can raise error 5: Access Denied Exceptions.

Using [DirectoryEnumerationFilters](https://github.com/alphaleonis/AlphaFS/blob/f59b649327af60bbfaed3d06e6618f991863d848/AlphaFS/Filesystem/Structures%20And%20Enumerations/DirectoryEnumerationFilters.cs) enumerating can report these exceptions and continue.

Added bonus is additional folder/file criteria filtering: [Example/Unit Test](https://github.com/alphaleonis/AlphaFS/blob/82e129bc4bd2d347fab659b3f229aa77c53f123d/AlphaFS.UnitTest/Directory%20Class/AlphaFS_Directory_EnumerateFiles_UsingDirectoryEnumerationFilters.cs)

**Comment by RandomSheeple** [comment]
Pardon my ignorance in case this question is silly, but how would this play out with .net existing error handling methodologies?
Specifically parallel.foreach when run from a task factory does not allow for exception handling in there without dying a horrible messy convoluted death when enumerating 100 000's of folders and millions of files in parallel.
Currently I am running into these errors in a 
 await Task.Factory.StartNew(() => Parallel.ForEach(rootFolders, (currentFolder) =>
          {
              try
              {
                 //do something with
			Alphaleonis.Win32.Filesystem.DirectoryInfo.GetDirectories();
                //that causes exception (mambo) #5 like try to access recycle bin, volume info etc
              }
              catch (Exception ex) { ExceptionQ.Enqueue(ex); }
	}));
When queuing up errors  in a ConcurrentQueue I can just handle them in a managed way single thread in the caller after all is done.


ref: https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops

**Comment by Yomodo** [comment]
The AlphaFS .NET implementations will remain as-is.

I haven't tried the DirectoryEnumerationFilters yet in a parallel context, so I'm not sure how that will turn out. For "normal" processing, these filters work well.
