### ISSUE TITLE
Documentation needs a major review

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#4]
There are a ton of warnings about unresolved links, and in many cases the Remarks-section is nested _inside_ the `<summary>` tags which creates bad output. Review this and try to fix these issues.

**Comment by alphaleonis** [comment]
Why the label changes? I was just about to start with this one but see you changed it from bug to discussion... and then to nothing... Can I assume this was inadvertently, or did you have some objections to this? ;)

**Comment by Yomodo** [comment]
Yes my bad, inadvertently.
