### ISSUE TITLE
After formatting , DirectoryInfo.GetFileSystemInfos throw DirectoryNotFoundException

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#41]
_Issue by **[hnorihiro](https://github.com/hnorihiro)** from Friday Jan 09, 2015 at 11:16 GMT_
_Originally opened as https://github.com/alphaleonis/AlphaFS/issues/41_

---

1.I **format** the G drive

2.
AlphaFS(2015/1/8)

```
DirectoryInfo info = new DirectoryInfo(@"G:\");
info.GetFileSystemInfos();//Directory not found Exception
```

.NET

```
System.IO.DirectoryInfo info = new System.IO.DirectoryInfo(@"G:\");
info.GetFileSystemInfos();//Success!!
```

Can you help me?

**Comment by alphaleonis** [comment]
_Comment by **[Yomodo](https://github.com/Yomodo)** from Friday Jan 09, 2015 at 11:35 GMT_

----

What type of device is G:  (external drive, USB stick, ...)
NTFS formatting?

**Comment by alphaleonis** [comment]
_Comment by **[hnorihiro](https://github.com/hnorihiro)** from Wednesday Jan 14, 2015 at 01:03 GMT_

----

Yes, it is NTFS(USB Drive).
Drive When it is empty after formatting, occurs error.
Drive When $RECYCLE.BIN exist,does not occurs.

**Comment by alphaleonis** [comment]
_Comment by **[Yomodo](https://github.com/Yomodo)** from Wednesday Jan 14, 2015 at 23:24 GMT_

----

Does it still throw the exception if you execute: ```info.Refresh();``` first?

**Comment by alphaleonis** [comment]
_Comment by **[hnorihiro](https://github.com/hnorihiro)** from Thursday Jan 15, 2015 at 01:49 GMT_

----

OS Windows7
.NET 3.5

```
DirectoryInfo info = new DirectoryInfo(@"G:\");
info.Refresh();
info.GetFileSystemInfos();//Directory not found Exception
```
it still throw the exception .

**Comment by alphaleonis** [comment]
_Comment by **[Yomodo](https://github.com/Yomodo)** from Thursday Jan 15, 2015 at 10:14 GMT_

---

Confirmed on Windows 8.1 X64

It seems related to the volume label.
The exception can be avoided with: `/v:myLabel`
But even then I still see the Exception thrown, sometimes.

```
var drive = @"D:";
var format_cmd = "/C format.com " + drive + " /fs:NTFS /v:myLabel /q";

using (var process = Process.Start("CMD.exe", format_cmd))
    process.WaitForExit();

DirectoryInfo info = new DirectoryInfo(drive + @"\");
info.GetFileSystemInfos();
```

However, System.IO indeed does not throw an Exception.

**Comment by Yomodo** [comment]
Unfortunately, I could not find anything to fix within AlphaFS.

The only possbile _fix_ for this issue,
is to add a: `Thread.Sleep(1000);` before calling `DirectoryInfo()`.
