### ISSUE TITLE
Different behavior between System.IO.File.Open / Alphaleonis.Win32.Filesystem.File.Open

### ISSUE THREAD

**Issue by Ash014** [alphaleonis/AlphaFS#438]
I'm trying to use AlphaFS in order to replace System.IO in my application.

I have a different behavior when I use System.IO.File.Open() and Alphaleonis.Win32.Filesystem.File.Open().
The variable "Name" of FileStream object indicates "Unknow" with Alphaleonis.Win32.Filesystem lib while the System.IO lib indicates the full path of my file.

`FileStream fs = Alphaleonis.Win32.Filesystem.File.Open(filepath, System.IO.FileMode.Open, System.IO.FileAccess.ReadWrite, System.IO.FileShare.None);`

fs.Name => "Unknow"

`FileStream fs = System.IO.File.Open(filepath, System.IO.FileMode.Open, System.IO.FileAccess.ReadWrite, System.IO.FileShare.None);`

fs.Name => "C:/....."

Do you have an idea to solve that?

**Comment by Yomodo** [comment]
It seems that the text: "[Unknown]" is inside .NET: [IO_UnknownFileName = [Unknown]](https://github.com/Microsoft/referencesource/blob/b31308b03e8bd5bf779fb80fda71f31eb959fe0b/mscorlib/mscorlib.txt#L1883)

Unfortunately, I failed to figure out why this value is returned.

**Comment by Yomodo** [comment]
It seems you can use this to still get the full path:

    using (var fs = Alphaleonis.Win32.Filesystem.File.Open(filepath, FileMode.Open, FileAccess.ReadWrite, FileShare.None))
    {
        var path = Alphaleonis.Win32.Filesystem.Path.GetRegularPath(Alphaleonis.Win32.Filesystem.Path.GetFinalPathNameByHandle(fs.SafeFileHandle));

        Console.WriteLine(path);
    }
