### ISSUE TITLE
InvalidOperationException on Directory.EnumerateFileSystemEntries()

### ISSUE THREAD

**Issue by CyberSinh** [alphaleonis/AlphaFS#441]
Hi,

If I run these commands under PowerShell:

```powershell
$path = "\\Ds216j\sauvegardes\Documents" # it's a shared folder on a Synology NAS
[Alphaleonis.Win32.Filesystem.Directory]::GetFileSystemEntryInfo($path)
[Alphaleonis.Win32.Filesystem.Directory]::EnumerateFileSystemEntries($path)
```
I get the following output:

![1526105805067blob](https://user-images.githubusercontent.com/10407531/39957169-c4b2811a-55ee-11e8-9b55-248854258805.jpg)

As you can see, the target folder is well identified as a directory by AlphaFS. However, if I try to enumerate the contents of this folder, I get an error "the target directrory is a file, not a directory".
Does anybody know why?

Thanks.

**Comment by Yomodo** [comment]
curious.. how about other unc/local paths?
It think that the problem is not the path itself (\\\\Ds216j\sauvegardes\Documents), but the
next folder or file that is returned by the enumeration. InvalidOperationException can point
to a cyclic operation.

**Comment by fwi98** [comment]
Ok . How can i see the "next folder or file returned" ? NAS logs or PC logs?
Some folder are OK , other not.
Thanks
Regards

**Comment by Yomodo** [comment]
Hm.. the only way I can think of is using the VS debugger.

**Comment by CyberSinh** [comment]
Hi Yomodo.
You will find attached the IntelliTrace file sent by the end user affected by this issue. 
Hope you will find it useful to diagnoose the issue. 
Thanks.

[AlphaFS.itrace.zip](https://github.com/alphaleonis/AlphaFS/files/2018603/AlphaFS.itrace.zip)

**Comment by CyberSinh** [comment]
Hi Yomodo. Was this iTrace file useful to you? Do you need more information?

**Comment by Yomodo** [comment]
Hi CyberSinh, thanks for this. Will analyze this in the next days.

**Comment by Yomodo** [comment]
Unfortunately, I only have access to VS 2015 Enterprise, loading the .Itrace throws a waring that I'm not able to view all the information.

However, the Exception is thrown here: https://github.com/alphaleonis/AlphaFS/blob/3e87fdec1d8cb15f2ecaf9f11ad6e1f62d17103d/AlphaFS/Filesystem/FindFileSystemEntryInfo.cs#L427

If you can place a breakpoint and run debug again, you should be able to see exactly what data *win32FindData* and *regularPath* contain. Hopefully this can tell us more.

**Comment by CyberSinh** [comment]
Hi Yomodo,
You will find below a screenshot of Visual Studio 2017 with the iTrace log file opened:
![debug](https://user-images.githubusercontent.com/10407531/40455469-53d57058-5eed-11e8-941f-2eb90e4f84c4.png)

You can view the _win32FindData_ variable data.

**Comment by Yomodo** [comment]
I think the fix is simple; could you change this line: https://github.com/alphaleonis/AlphaFS/blob/3e87fdec1d8cb15f2ecaf9f11ad6e1f62d17103d/AlphaFS/Filesystem/FindFileSystemEntryInfo.cs#L303
to: `if (null != handle && lastError != Win32Errors.NO_ERROR)`

**Comment by CyberSinh** [comment]
Thank you very much Yomodo!

**Comment by Yomodo** [comment]
It works? Cool!

**Comment by CyberSinh** [comment]
I will propose a modified version of AlphaFS to the user concerned by this issue to check if the patch works. I'll keep you informed.

**Comment by CyberSinh** [comment]
I'm sorry but the user concerned has told me that the patch does not work. The same error always occurs. Here is the new IntelliTrace log:
[AlphaFS2.zip](https://github.com/alphaleonis/AlphaFS/files/2040882/AlphaFS2.zip)

**Comment by Yomodo** [comment]
I've made a new branch [#441](https://github.com/alphaleonis/AlphaFS/branches) based on the latest master. Could you test again with this?

**Comment by CyberSinh** [comment]
Everything works fine with this new branch. You can merge it. Thank you.

**Comment by CyberSinh** [comment]
Any timinig for a new maintenance nuget release?

**Comment by Yomodo** [comment]
Soon, I'll start preparing.
