### ISSUE TITLE
Directory.Delete(, true, true) occasionally throws DirectoryNotEmptyException.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#480]
`Alphaleonis.Win32.Filesystem.DirectoryNotEmptyException: (145) The directory is not empty`

Indeed not all folders are empty upon deletion.

**Comment by astrohart** [comment]
I do not think that this issue should be closed, as I have experienced this just now, 27 Oct 2021, 1639 Central time (USA).
