### ISSUE TITLE
Improve file system enumeration using Span<char>

### ISSUE THREAD

**Issue by CyberSinh** [alphaleonis/AlphaFS#483]
Hi,

In .NET Core 2.1, file enumerations are very powerful due to the use of `Span<char>`. You can read for example this blog post : [performance improvements in .NET Core 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1/)

Is AlphaFS planning to use the new opportunities offered by these new types to improve performance, especially in terms of reduced memory allocation?

Thanks.

**Comment by Yomodo** [comment]
Certainly looks impressive!
Currently there are no concrete plans to implement this on a short notice.

**Comment by alphaleonis** [comment]
Is the Span<> feature released in final yet?

**Comment by Yomodo** [comment]
Yep, seems like it.

**Comment by CyberSinh** [comment]
I'm closing this issue as there are no further developments to be expected from AlphaFS. 
Is AlphaFS dead ? #529
