### ISSUE TITLE
Path.CheckInvalidPathChars in Path.Helpers.cs should be case insensitive

### ISSUE THREAD

**Issue by GuyTe** [alphaleonis/AlphaFS#488]
If you have a path like this (notice the GLOBALROOT uppercase):

`
string srcPath = @"\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy19\Windows\system32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Adobe-Flash-For-Windows-Package~31bf3856ad364e35~amd64~~6.3.9600.16384.cat";
`

The below code breaks:

         if (pathRp.StartsWith(GlobalRootPrefix, StringComparison.OrdinalIgnoreCase))
            pathRp = pathRp.Replace(GlobalRootPrefix, string.Empty);  // <= bug. Replace is case sensitive

         if (pathRp.StartsWith(VolumePrefix, StringComparison.OrdinalIgnoreCase))
            pathRp = pathRp.Replace(VolumePrefix, string.Empty);  // <= bug. Replace is case sensitive

An alternative might be:

            if (pathRp.StartsWith(GlobalRootPrefix, StringComparison.OrdinalIgnoreCase))
                pathRp = Regex.Replace(pathRp, Regex.Escape(GlobalRootPrefix), string.Empty, RegexOptions.IgnoreCase);
            if (pathRp.StartsWith(VolumePrefix, StringComparison.OrdinalIgnoreCase))
                pathRp = Regex.Replace(pathRp, Regex.Escape(VolumePrefix), string.Empty);

**Comment by Yomodo** [comment]
Thanks for reporting. Should be fixed now.

**Comment by Yomodo** [comment]
The unit test is flawed; it does not work correct yet.
