### ISSUE TITLE
No way to instantiate FileIdBothDirectoryInfo

### ISSUE THREAD

**Issue by ashelleyPurdue** [alphaleonis/AlphaFS#496]
The class FileIdBothDirectoryInfo is exposed to consumers as public, and there's even documentation for it.  However, there doesn't appear to be a public constructor, or any other way to get your hands on one.  I did a quick "find all references" on the class name, and it looks like no other files in the project use it.

Was this class intended to be used by consumers?

**Comment by Yomodo** [comment]
Instances of this type can be obtained by using the [Alphaleonis.Win32.Filesystem.Directory.EnumerateFileIdBothDirectoryInfo](https://github.com/alphaleonis/AlphaFS/blob/master/AlphaFS/Filesystem/Directory%20Class/Directory.EnumerateFileIdBothDirectoryInfo.cs) method.
