### ISSUE TITLE
AlphaFS.dll - Minimum PowerShell Version Required

### ISSUE THREAD

**Issue by avi081265** [alphaleonis/AlphaFS#505]
We have different type of server and in process of creating file server inventory report (files and folders information).

Some of the file server are Windows Server 2008 with PowerShell 2.0 installed, will AlphaFS.dll support for PS ver 2.0?

Please confirm

Avian

**Comment by alphaleonis** [comment]
AlphaFS in its current version (2.2.x) should work in PowerShell 2.0 as well. But PowerShell 2.0 has been [deprecated by Microsoft](https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/), and future versions of AlphaFS will likely not support PowerShell 2.0 (without .NET Framework 4.5 and CLR4 runtime).

**Comment by avi081265** [comment]
Will this support Get-LongChildItem?
