### ISSUE TITLE
How to get the list of files between days

### ISSUE THREAD

**Issue by avi081265** [alphaleonis/AlphaFS#510]
How to get the list of files which are more than 180 days and less 360 days.

I also want to attributes (mentioned below) of each files
CreationTime,LastWriteTime, LastAccessTime,Extension,Length, Name, Directory, FullName, createdby, owner

Please advise.

**Comment by Yomodo** [comment]
[Import AlphaFS](https://github.com/alphaleonis/AlphaFS/wiki/PowerShell)

https://stackoverflow.com/questions/17366675/using-get-childitem-to-get-a-list-of-files-modified-in-the-last-3-days
