### ISSUE TITLE
Cancel a current copy-process?

### ISSUE THREAD

**Issue by NeobaThing** [alphaleonis/AlphaFS#521]
Hello,

at first thx for the fantastic Library :-)

My problem: I can´t find a way to cancel a current copy-process with Directory(Info) and File(Info). How can i stop this process?

regards

**Comment by Yomodo** [comment]
Hi, thank you.

Just like the System.IO implementation, AlphaFS implementations do not support this.

**Comment by NeobaThing** [comment]
OK :-)
