### ISSUE TITLE
.NET 5.0 support

### ISSUE THREAD

**Issue by CyberSinh** [alphaleonis/AlphaFS#522]
Hi,

I tried to use AlphaFS in a .NET 5.0 project and I get the following warning:

`Avertissement NU1701:	Le package 'AlphaFS 2.2.6' a été restauré en utilisant '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' au lieu du framework cible du projet 'net5.0-windows7.0'. Ce package n'est peut-être pas totalement compatible avec votre projet.`

Does the .NET 5.0 framework officially supported?

Thanks.

Regards,

Sylvain

**Comment by alphaleonis** [comment]
That sounds like complete French to me. 🤣 
But no, unfortunately .NET 5.0 is not (yet) supported.

**Comment by CyberSinh** [comment]
OK thanks. 
Do you have a roadmap for .NET 5.0 support?

**Comment by alphaleonis** [comment]
No, unfortunately I don't think we have a roadmap yet.  I haven't had time to investigate this personally yet, so don't quite know the scope of it. @Yomodo, do you have any input on this?

**Comment by CyberSinh** [comment]
What would need to be done to make AlphaFS officially compatible with .NET 5.0? As it is, the library seems to work without any problems.

**Comment by Yomodo** [comment]
Hi! Sorry for the delay.

I cannot believe I'm saying this, but apart from the NTFS specific stuff,
why would you still want to use AlphaFS on NET 5?

Guess "long path" is not an issue anymore?

**Comment by CyberSinh** [comment]
I don't see any API such as `Volume.GetUniqueVolumeNameForPath` in .NET 5 for eg.
Also, you don't have any way to enumerate file system entries with [filters](https://github.com/dotnet/runtime/issues/26710) like `ErrorFilter`.

**Comment by DPetersen257** [comment]
Poking this issue as I'm running into it...

Another reason for AlphaFS on .net 5 is that .net 5 doesn't seem to have any methods for converting to local to UNC paths.
I have a strong need in my app (both in .net standard and .net 5) to convert both local and remote paths to UNC format

Not sure why Windows supports working with UNC paths but can't convert to them...

**Comment by brisingraerowing** [comment]
I used a converter to convert the project to .NET 5. It doesn't appear that any changes were needed (from the Git stuff in VS), though I don't remember if I did change anything.

**Comment by CyberSinh** [comment]
I'm closing this issue as there are no further developments to be expected from AlphaFS. 
Is AlphaFS dead ? #529
