### ISSUE TITLE
Missing return value documentation in DirectoryInfo.MoveTo overload.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#58]
BuildAssembler : warning : ShowMissingComponent: [M:Alphaleonis.Win32.Filesystem.DirectoryInfo.MoveTo(System.String,Alphaleonis.Win32.Filesystem.PathFormat)] Missing <returns> documentation [D:\Coding\Projects\GitHub\AlphaFS\Bin\Documentation\Working\BuildReferenceTopics.proj]

**Comment by Yomodo** [comment]
Hm.. I really can't see in the source what is wrong? :|

**Comment by alphaleonis** [comment]
Line 263, in DirectoryInfo.CopyToMoveTo.cs, there is no `<returns>` documentation tag.
