### ISSUE TITLE
Remove all use of "Problematic" methods such as DangerousAddRef and DangerousGetHandle()

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#60]
_Issue by **[alphaleonis](https://github.com/alphaleonis)** from Saturday Jan 10, 2015 at 19:50 GMT_
_Originally opened as https://github.com/alphaleonis/AlphaFS/issues/60_

----

These methods should never be needed. We should use SafeHandles instead.

**Comment by alphaleonis** [comment]
_Comment by **[Yomodo](https://github.com/Yomodo)** from Saturday Jan 10, 2015 at 21:46 GMT_

----

As handle, SafeGlobalMemoryBufferHandle() is used.

DangerousGetHandle() is implemented because of Code Analysis Warning: "CA2001: Avoid calling problematic methods"

**Comment by alphaleonis** [comment]
_Comment by **[alphaleonis](https://github.com/alphaleonis)** from Saturday Jan 10, 2015 at 21:54 GMT_

----

The code analysis warning is *because* we are calling DangerousGetHandle(). There should not be a situation where this is needed.

**Comment by alphaleonis** [comment]
Have you considered not writing "Fixes" in the commit message if you don't want the issue to be closed? :wink:  (You can still refer to it by writing the id)

**Comment by Yomodo** [comment]
ah, yeah ofcourse :) thx.

Date: Sat, 17 Jan 2015 14:42:01 -0800

**Comment by alphaleonis** [comment]
@Yomodo Howcome this was moved to 2.0.1? Isn't all the changes so far made on the `develop` branch?

**Comment by Yomodo** [comment]
True, my bad. Again
