### ISSUE TITLE
Add ToString method to FileSystemEntryInfo class.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#85]
Currently it outputs the FileSystemEntryInfo instance type.

The ReparsePointTag information will be returned.

**Comment by Yomodo** [comment]
@alphaleonis "The ReparsePointTag information will be returned.",  what do you think?

**Comment by alphaleonis** [comment]
Sounds good, but why reopened?

**Comment by alphaleonis** [comment]
Ah, I see. ;)

**Comment by Yomodo** [comment]
I only wanted to close it after you saw it.
