### ISSUE TITLE
Add DirectoryReadOnlyException()

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#86]
Inherits from System.IO.IOException.

**Comment by alphaleonis** [comment]
Can a directory even be Read-only on an NTFS system?

**Comment by Yomodo** [comment]
Yup.

**Comment by alphaleonis** [comment]
[According to MSDN](http://msdn.microsoft.com/en-us/library/windows/desktop/aa365535%28v=vs.85%29.aspx):

`FILE_ATTRIBUTE_READONLY`
A file that is read-only. Applications can read the file, but cannot write to it or delete it. This attribute is not honored on directories. For more information, see "You cannot view or change the Read-only or the System attributes of folders in Windows Server 2003, in Windows XP, or in Windows Vista.

**Comment by Yomodo** [comment]
And yet, this works:

```
string dir = @"C:\_Junk\testFolder";

if (!System.IO.Directory.Exists(dir))
    System.IO.Directory.CreateDirectory(dir);

// Outputs: "Directory"
Console.WriteLine(System.IO.File.GetAttributes(dir));

System.IO.File.SetAttributes(dir, System.IO.FileAttributes.ReadOnly);

// Outputs: "ReadOnly, Directory"
Console.WriteLine(File.GetAttributes(dir));

// Throws: System.IO.IOException: Access to the path 'C:\_Junk\testFolder' is denied.
System.IO.Directory.Delete(dir);
```

**Comment by Yomodo** [comment]
I guess MSDN docs are incorrect.
Browsing .NET source reveals Win32Native.SetFileAttributes, used for directories.

**Comment by alphaleonis** [comment]
Okay, cool... Maybe it was just in earlier versions of windows then or something. I think you can't set it from Windows Explorer anyway, but then again, Windows Explorer doesn't support long paths either so I guess that's not a very good source for information ;)

**Comment by alphaleonis** [comment]
@Yomodo  but doesn't the new exception have the wrong error code? (DIR_NOT_EMPTY)?

**Comment by Yomodo** [comment]
@alphaleonis Right! That was a copy paste. grrrr
